<?php

declare(strict_types=1);

$options = [
    'home' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
                [
                    'name' => 'options[primary_title]',
                    'id' => 'primary_title',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Title',
                    'default' => 'Primary Section Title',
                ],
            ],
        ],
        [
            'section_title' => 'Shortcut Links Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'shortcut_links_list',
                    'type' => 'array',
                    'label' => 'List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[shortcut_links_list][shortcut_title]',
                            'id' => 'shortcut_title',
                            'type' => 'text',
                            'label' => 'Title',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[shortcut_links_list][shortcut_description]',
                            'id' => 'shortcut_description',
                            'type' => 'text',
                            'label' => 'Description',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[shortcut_links_list][shortcut_url]',
                            'id' => 'shortcut_url',
                            'type' => 'text',
                            'label' => 'Button Url',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[shortcut_links_list][shortcut_image]',
                            'id' => 'shortcut_image',
                            'type' => 'file',
                            'label' => 'Image',
                            'default' => '',
                        ],
                    ],
                    'display_fields' => [
                        'shortcut_title' => 'Title',
                    ],
                ],
            ],
        ],
        [
            'section_title' => 'Featured Properties Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[feature_properties_bg_color]',
                    'id' => 'feature_properties_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Background Color',
                    'default' => '#f0efef',
                ],
                [
                    'name' => 'options[feature_properties_title]',
                    'id' => 'feature_properties_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Prime Properties For Sale',
                ],
                [
                    'name' => 'options[feature_properties_sub_title]',
                    'id' => 'feature_properties_sub_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'RECENTLY ADDED',
                ],
                [
                    'name' => 'options[feature_properties_btn_label]',
                    'id' => 'feature_properties_btn_label',
                    'type' => 'text',
                    'label' => 'Button label',
                    'default' => 'VIEW ALL PROPERTIES',
                ],
            ],
        ],
        [
            'section_title' => 'Carousel Properties Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[carousel_properties_title]',
                    'id' => 'carousel_properties_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Superior Housing expertise',
                ],
                [
                    'name' => 'options[carousel_properties_sub_title]',
                    'id' => 'carousel_properties_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'HOUSES FOR SALE',
                ],
                [
                    'name' => 'options[carousel_properties_btn_label]',
                    'id' => 'carousel_properties_btn_label',
                    'type' => 'text',
                    'label' => 'Button label',
                    'default' => 'VIEW ALL PROPERTIES',
                ],
            ],
        ],
        [
            'section_title' => 'Info Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[info_section_bg_color]',
                    'id' => 'info_section_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Background Color',
                    'default' => '#f0efef',
                ],
                [
                    'name' => 'info_section_list',
                    'type' => 'array',
                    'label' => 'List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[info_section_list][info_section_title]',
                            'id' => 'info_section_title',
                            'type' => 'text',
                            'label' => 'Title',
                            'default' => 'Lifestyle',
                        ],
                        [
                            'name' => 'options[info_section_list][info_section_sub_title]',
                            'id' => 'info_section_sub_title',
                            'type' => 'text',
                            'label' => 'Sub Title',
                            'default' => 'THE ULTIMATE IN LOCATION & PRESTIGE',
                        ],
                        [
                            'name' => 'options[info_section_list][info_section_description]',
                            'id' => 'info_section_description',
                            'type' => 'text',
                            'label' => 'Description',
                            'default' => 'Our mission is to simplify your life and find the most prestigious properties for you to view.',
                        ],
                        [
                            'name' => 'options[info_section_list][info_section_btn_label]',
                            'id' => 'info_section_btn_label',
                            'type' => 'text',
                            'label' => 'Button label',
                            'default' => 'MORE',
                        ],
                        [
                            'name' => 'options[info_section_list][info_section_btn_url]',
                            'id' => 'info_section_btn_url',
                            'type' => 'text',
                            'label' => 'Button Url',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[info_section_list][info_section_image]',
                            'id' => 'info_section_image',
                            'type' => 'file',
                            'label' => 'Image',
                            'default' => '',
                        ],
                    ],
                    'display_fields' => [
                        'info_section_title' => 'Title',
                        'info_section_sub_title' => 'Sub Title',
                    ],
                ],
            ],
        ],
        [
            'section_title' => 'News Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[news_title]',
                    'id' => 'news_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Follow us to stay informed',
                ],
                [
                    'name' => 'options[news_sub_title]',
                    'id' => 'news_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Market News',
                ],
            ],
        ],
        [
            'section_title' => 'About Us Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[about_us_title]',
                    'id' => 'about_us_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Premier service with passion!',
                ],
                [
                    'name' => 'options[about_us_sub_title]',
                    'id' => 'about_us_sub_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'PRESTIGE REAL ESTATE SELECTION',
                ],
                [
                    'name' => 'options[about_us_description]',
                    'id' => 'about_us_description',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => 'Description',
                    'default' => 'About Us Description',
                ],
                [
                    'name' => 'options[about_us_image]',
                    'id' => 'about_us_image',
                    'type' => 'file',
                    'label' => 'Image',
                ],
                [
                    'name' => 'options[about_us_bg_color]',
                    'id' => 'about_us_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Background Color',
                    'default' => '#f0efef',
                ],
                [
                    'name' => 'form_section',
                    'id' => 'form_section',
                    'type' => 'title',
                    'label' => 'Enquiry Form',
                ],
                [
                    'name' => 'options[contact_form_bg_color]',
                    'id' => 'contact_form_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Background Color',
                    'default' => '#b1aa9c33',
                ],
                [
                    'name' => 'options[contact_form_name]',
                    'id' => 'contact_form_name',
                    'type' => 'text',
                    'label' => 'Full Name Label',
                    'default' => 'Full Name',
                ],
                [
                    'name' => 'options[contact_form_email]',
                    'id' => 'contact_form_email',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email',
                ],
                [
                    'name' => 'options[contact_form_phone]',
                    'id' => 'contact_form_phone',
                    'type' => 'text',
                    'label' => 'Phone Label',
                    'default' => 'Phone Number',
                ],
                [
                    'name' => 'options[contact_form_message]',
                    'id' => 'contact_form_message',
                    'type' => 'text',
                    'label' => 'Message Label',
                    'default' => 'Message',
                ],
                [
                    'name' => 'options[contact_form_btn]',
                    'id' => 'contact_form_btn',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Submit',
                ],
            ],
        ],
    ],
    'property' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[primary_bg_image]',
                    'id' => 'primary_bg_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
            ],
        ],
        [
            'section_title' => 'Property Description Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[property_desc_title]',
                    'id' => 'property_desc_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'PROPERTY DESCRIPTION',
                ],
                [
                    'name' => 'options[property_enquire_btn_label]',
                    'id' => 'property_enquire_btn_label',
                    'type' => 'text',
                    'label' => 'Enquire Label',
                    'default' => 'ENQUIRE',
                ],
                [
                    'name' => 'options[property_brochure_btn_label]',
                    'id' => 'property_brochure_btn_label',
                    'type' => 'text',
                    'label' => 'Brochure Label',
                    'default' => 'DOWNLOAD BROCHURE',
                ],
            ],
        ],
        [
            'section_title' => 'Enquiry Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_form_title]',
                    'id' => 'contact_form_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Enquiry title',
                    'default' => 'ENQUIRE',
                ],
                [
                    'name' => 'options[contact_form_bg_color]',
                    'id' => 'contact_form_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Background Color',
                    'default' => '#b1aa9c33',
                ],
                [
                    'name' => 'options[contact_form_name]',
                    'id' => 'contact_form_name',
                    'type' => 'text',
                    'label' => 'Full Name Label',
                    'default' => 'Full Name',
                ],
                [
                    'name' => 'options[contact_form_email]',
                    'id' => 'contact_form_email',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email',
                ],
                [
                    'name' => 'options[contact_form_phone]',
                    'id' => 'contact_form_phone',
                    'type' => 'text',
                    'label' => 'Phone Label',
                    'default' => 'Phone Number',
                ],
                [
                    'name' => 'options[contact_form_message]',
                    'id' => 'contact_form_message',
                    'type' => 'text',
                    'label' => 'Message Label',
                    'default' => 'Message',
                ],
                [
                    'name' => 'options[contact_form_btn]',
                    'id' => 'contact_form_btn',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Submit',
                ],
            ],
        ],
    ],
    'properties' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[primary_section_sub_title]',
                    'id' => 'primary_section_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'PROPERTIES',
                ],
                [
                    'name' => 'options[primary_section_title]',
                    'id' => 'primary_section_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'OUR PREMIUM PROPERTIES',
                ],
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Primary Section Image',
                ],
            ],
        ],
    ],
    'blog' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[blog_content]',
                    'id' => 'blog_content',
                    'type' => 'advance-html-editor',
                    'group_width' => 'full',
                    'label' => 'News Content',
                    'default' => 'News',
                ],
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
            ],
        ],
    ],
    'components/footer' => [
        [
            'section_title' => 'Footer Image',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[footer_image]',
                    'id' => 'footer_image',
                    'type' => 'file',
                    'label' => 'Image',
                ],
                [
                    'name' => 'options[newsletter_description]',
                    'id' => 'newsletter_description',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Get early access to new properties.',
                ],
                [
                    'name' => 'options[newsletter_email_label]',
                    'id' => 'newsletter_email_label',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email',
                ],
                [
                    'name' => 'options[newsletter_btn]',
                    'id' => 'newsletter_btn',
                    'type' => 'text',
                    'label' => 'Submit Label',
                    'default' => 'SIGN UP',
                ],
            ],
        ],
        [
            'section_title' => 'Newsletter Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[newsletter_title]',
                    'id' => 'newsletter_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'NEWSLETTER',
                ],
                [
                    'name' => 'options[newsletter_description]',
                    'id' => 'newsletter_description',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Get early access to new properties.',
                ],
                [
                    'name' => 'options[newsletter_email_label]',
                    'id' => 'newsletter_email_label',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email',
                ],
                [
                    'name' => 'options[newsletter_btn]',
                    'id' => 'newsletter_btn',
                    'type' => 'text',
                    'label' => 'Submit Label',
                    'default' => 'SIGN UP',
                ],
            ],
        ],
    ],
    'contact' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
            ],
        ],
        [
            'section_title' => 'Contact Form Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_form_title]',
                    'id' => 'contact_form_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Title',
                    'default' => 'SEND US A MESSAGE',
                ],
                [
                    'name' => 'options[contact_form_bg_color]',
                    'id' => 'contact_form_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Background Color',
                    'default' => '#b1aa9c33',
                ],
                [
                    'name' => 'options[contact_form_name]',
                    'id' => 'contact_form_name',
                    'type' => 'text',
                    'label' => 'Full Name Label',
                    'default' => 'Your Name',
                ],
                [
                    'name' => 'options[contact_form_email]',
                    'id' => 'contact_form_email',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Your Email',
                ],
                [
                    'name' => 'options[contact_form_phone]',
                    'id' => 'contact_form_phone',
                    'type' => 'text',
                    'label' => 'Phone Label',
                    'default' => 'Your Phone',
                ],
                [
                    'name' => 'options[contact_form_message]',
                    'id' => 'contact_form_message',
                    'type' => 'text',
                    'label' => 'Message Label',
                    'default' => 'Your Message(Optional)',
                ],
                [
                    'name' => 'options[contact_form_btn]',
                    'id' => 'contact_form_btn',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Submit',
                ],
            ],
        ],
        [
            'section_title' => 'Map Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[coordinates]',
                    'id' => 'coordinates',
                    'type' => 'text',
                    'label' => 'Coordinates',
                    'default' => '',
                ],
                [
                    'name' => 'options[map_title]',
                    'id' => 'map_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'HOW CAN WE HELP?',
                ],
                [
                    'name' => 'options[map_description]',
                    'id' => 'map_description',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => '<p>Thank you for considering us as to assist you with your property requirements.</p>',
                ],
            ],
        ],
    ],
    'about' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
                [
                    'name' => 'options[about_title]',
                    'id' => 'about_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'About',
                ],
            ],
        ],
        [
            'section_title' => 'Team Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[about_team_title]',
                    'id' => 'about_team_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'group_width' => 'full',
                    'default' => 'Our Team',
                ],
                [
                    'name' => 'options[about_content_1]',
                    'id' => 'about_content_1',
                    'type' => 'normal-html-editor',
                    'label' => 'Content 1',
                    'default' => '',
                ],
                [
                    'name' => 'options[about_team_image_1]',
                    'id' => 'about_team_image_1',
                    'type' => 'file',
                    'label' => 'Team Image 1',
                ],
                [
                    'name' => 'options[about_content_2]',
                    'id' => 'about_content_2',
                    'type' => 'normal-html-editor',
                    'label' => 'Content 2',
                    'default' => '',
                ],
                [
                    'name' => 'options[about_team_image_2]',
                    'id' => 'about_team_image_2',
                    'type' => 'file',
                    'label' => 'Team Image 2',
                ],
            ],
        ],
        [
            'section_title' => 'Contact Form Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_form_title]',
                    'id' => 'contact_form_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Get in touch today to find your dream property.',
                ],
                [
                    'name' => 'options[contact_form_bg_color]',
                    'id' => 'contact_form_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Background Color',
                    'default' => '#b1aa9c33',
                ],
                [
                    'name' => 'options[contact_form_name]',
                    'id' => 'contact_form_name',
                    'type' => 'text',
                    'label' => 'Full Name Label',
                    'default' => 'Full Name',
                ],
                [
                    'name' => 'options[contact_form_email]',
                    'id' => 'contact_form_email',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email',
                ],
                [
                    'name' => 'options[contact_form_phone]',
                    'id' => 'contact_form_phone',
                    'type' => 'text',
                    'label' => 'Phone Label',
                    'default' => 'Phone Number',
                ],
                [
                    'name' => 'options[contact_form_message]',
                    'id' => 'contact_form_message',
                    'type' => 'text',
                    'label' => 'Message Label',
                    'default' => 'Message',
                ],
                [
                    'name' => 'options[contact_form_btn]',
                    'id' => 'contact_form_btn',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Submit',
                ],

            ],
        ],
    ],
    'blogs' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
                [
                    'name' => 'options[blogs_card_btn]',
                    'id' => 'blogs_card_btn',
                    'type' => 'text',
                    'label' => 'News Card Button Text',
                    'default' => 'Read more',
                ],
            ],
        ],
    ],
    'wishlist' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[section_title]',
                    'id' => 'section_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Section Title',
                    'default' => 'Your favourites',
                ],
            ],
        ],
    ],
    'discover' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
            ],
        ],
        [
            'section_title' => 'Section List',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'discover_list',
                    'type' => 'array',
                    'label' => 'List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[discover_list][discover_list_title]',
                            'id' => 'discover_list_title',
                            'type' => 'text',
                            'label' => 'Title',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[discover_list][discover_list_description]',
                            'id' => 'discover_list_description',
                            'type' => 'simple-html-editor',
                            'label' => 'Description',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[discover_list][discover_list_img]',
                            'id' => 'discover_list_img',
                            'type' => 'file',
                            'label' => 'Background Image',
                            'default' => '',
                        ],
                    ],
                    'display_fields' => [
                        'discover_list_title' => 'Title',
                    ],
                ],
            ],
        ],
    ],
    'cookie_policy' => [
        [
            'section_title' => 'Cookie Policy Content',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'group_width' => 'full',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
                [
                    'name' => 'options[cookie_content]',
                    'id' => 'cookie_content',
                    'group_width' => 'full',
                    'type' => 'advance-html-editor',
                    'label' => 'Content',
                    'default' => 'Content',
                ],
            ],
        ],
    ],
    'privacy_policy' => [
        [
            'section_title' => 'Privacy Policy',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'group_width' => 'full',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
                [
                    'name' => 'options[privacy_content]',
                    'id' => 'privacy_content',
                    'group_width' => 'full',
                    'type' => 'advance-html-editor',
                    'label' => 'Content',
                    'default' => 'Content',
                ],
            ],
        ],
    ],
    'list_a_property' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
            ],
        ],
        [
            'section_title' => 'List a Property Form Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_form_title]',
                    'id' => 'contact_form_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Complete the form below to list your property for sale or rent with us.',
                ],
                [
                    'name' => 'options[contact_form_name]',
                    'id' => 'contact_form_name',
                    'type' => 'text',
                    'label' => 'Full Name Label',
                    'default' => 'Full Name',
                ],
                [
                    'name' => 'options[contact_form_email]',
                    'id' => 'contact_form_email',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email',
                ],
                [
                    'name' => 'options[contact_form_phone]',
                    'id' => 'contact_form_phone',
                    'type' => 'text',
                    'label' => 'Phone Label',
                    'default' => 'Phone Number',
                ],
                [
                    'name' => 'options[contact_form_beds]',
                    'id' => 'contact_form_beds',
                    'type' => 'text',
                    'label' => 'Bedrooms Label',
                    'default' => 'Bedrooms',
                ],
                [
                    'name' => 'options[contact_form_baths]',
                    'id' => 'contact_form_baths',
                    'type' => 'text',
                    'label' => 'Bathrooms Label',
                    'default' => 'Bathrooms',
                ],
                [
                    'name' => 'options[contact_form_property_sale_rent]',
                    'id' => 'contact_form_property_sale_rent',
                    'type' => 'text',
                    'label' => 'Sale/Rent Label',
                    'default' => 'Property for Sale or Rent?',
                ],
                [
                    'name' => 'options[contact_form_property_type]',
                    'id' => 'contact_form_property_type',
                    'type' => 'text',
                    'label' => 'Property Type Label',
                    'default' => 'Property Type',
                ],
                [
                    'name' => 'options[contact_form_location]',
                    'id' => 'contact_form_location',
                    'type' => 'text',
                    'label' => 'Location Label',
                    'default' => 'Location',
                ],
                [
                    'name' => 'options[contact_form_covered_area]',
                    'id' => 'contact_form_covered_area',
                    'type' => 'text',
                    'label' => 'Covered area Label',
                    'default' => 'Covered Area',
                ],
                [
                    'name' => 'options[contact_form_plot_size]',
                    'id' => 'contact_form_plot_size',
                    'type' => 'text',
                    'label' => 'Plot size Label',
                    'default' => 'Plot Size',
                ],
                [
                    'name' => 'options[contact_form_message]',
                    'id' => 'contact_form_message',
                    'type' => 'text',
                    'label' => 'Message Label',
                    'default' => 'Description / Notes',
                ],
                [
                    'name' => 'options[contact_form_agreement]',
                    'id' => 'contact_form_agreement',
                    'type' => 'simple-html-editor',
                    'label' => 'Agreement text',
                    'default' => '<p>I have read & understood the <a href="/privacy-policy" target="_blank">Privacy Policy</a></p>',
                ],
                [
                    'name' => 'options[contact_form_btn]',
                    'id' => 'contact_form_btn',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Submit',
                ],
            ],
        ],
    ],
];
