<?php
declare(strict_types=1);

$options = [
    'site_details' => [
        [
            'section_title' => 'Website Name',
            'section_description' => 'Provide a new name for your website',
            'fields' => [
                [
                    'name' => 'site_title',
                    'type' => 'text',
                    'label' => 'Name of Website',
                    'required' => true,
                ],
                [
                    'name' => 'theme',
                    'type' => 'hidden',
                    'label' => 'Theme',
                ],
            ],
        ],
        [
            'section_title' => 'Contact Details',
            'section_description' => 'The information users will use to contact you',
            'fields' => [
                [
                    'name' => 'email',
                    'type' => 'text',
                    'label' => 'Email',
                    'required' => true,
                ],
                [
                    'name' => 'phone',
                    'type' => 'text',
                    'label' => 'Phone',
                    'required' => true,
                ],
                [
                    'name' => 'options[whatsapp]',
                    'id' => 'whatsapp',
                    'type' => 'text',
                    'label' => 'WhatsApp',
                ],
                [
                    'name' => 'address',
                    'type' => 'text',
                    'label' => 'Address',
                ],
            ],
        ],
        [
            'section_title' => 'Social Media',
            'section_description' => 'The information users will use to contact you',
            'fields' => [
                [
                    'name' => 'options[social_media_facebook]',
                    'id' => 'social_media_facebook',
                    'type' => 'text',
                    'label' => 'Facebook',
                ],
                [
                    'name' => 'options[social_media_twitter]',
                    'id' => 'social_media_twitter',
                    'type' => 'text',
                    'label' => 'Twitter',
                ],
                [
                    'name' => 'options[social_media_linkedin]',
                    'id' => 'social_media_linkedin',
                    'type' => 'text',
                    'label' => 'LinkedIn',
                ],
                [
                    'name' => 'options[social_media_youtube]',
                    'id' => 'social_media_youtube',
                    'type' => 'text',
                    'label' => 'Youtube',
                ],
                [
                    'name' => 'options[social_media_tiktok]',
                    'id' => 'social_media_tiktok',
                    'type' => 'text',
                    'label' => 'TikTok',
                ],
                [
                    'name' => 'options[social_media_instagram]',
                    'id' => 'social_media_instagram',
                    'type' => 'text',
                    'label' => 'Instagram',
                ],
            ],
        ],
    ],
    'appearance' => [
        [
            'section_title' => 'Appearance',
            'section_description' => 'Style & personalize your site',
            'fields' => [
                [
                    'name' => 'options[style_primary_color]',
                    'id' => 'style_primary_color',
                    'type' => 'color-picker',
                    'label' => 'Site Primary Color',
                    'default' => '#FF4D00',
                ],
                [
                    'name' => 'options[style_secondary_color]',
                    'id' => 'style_secondary_color',
                    'type' => 'color-picker',
                    'label' => 'Site Secondary Color',
                    'default' => '#FFFFFF',
                ],
                [
                    'name' => 'logo',
                    'type' => 'file',
                    'label' => 'Menu logo',
                ],
                [
                    'name' => 'options[logo_light]',
                    'id' => 'logo_light',
                    'type' => 'file',
                    'label' => 'Menu logo (light)',
                ],
                [
                    'name' => 'options[favicon]',
                    'id' => 'favicon',
                    'type' => 'file',
                    'label' => 'Favicon',
                ],
                [
                    'name' => 'options[brochure_template_id]',
                    'id' => 'brochure_template_id',
                    'type' => 'select-ajax',
                    'label' => 'Brochure Template',
                    'default' => \App\Connector\DynamicTemplates::getIdByName('Comprehensive Brochure'),
                ],
            ],
        ],
        [
            'section_title' => 'Map',
            'section_description' => 'Map Settings',
            'fields' => [
                [
                    'name' => 'options[map_marker]',
                    'id' => 'map_marker',
                    'type' => 'file',
                    'label' => 'Pin',
                ],
                [
                    'name' => 'options[map_marker_active]',
                    'id' => 'map_marker_active',
                    'type' => 'file',
                    'label' => 'Pin when active',
                ],
                [
                    'name' => 'options[map_marker_width]',
                    'id' => 'map_marker_width',
                    'type' => 'text',
                    'label' => 'Pin width (px)',
                    'default' => '30',
                ],
                [
                    'name' => 'options[map_marker_height]',
                    'id' => 'map_marker_height',
                    'type' => 'text',
                    'label' => 'Pin height (px)',
                    'default' => '55',
                ],
                [
                    'name' => 'options[map_coords_random]',
                    'id' => 'map_coords_random',
                    'type' => 'select',
                    'label' => 'Random coordinates',
                    'placeholder' => 'Random coordinates',
                    'options' => [
                        'inherit' => 'Inherit From Qobrix',
                        'random' => 'Random Coordinates',
                    ],
                    'default' => 'inherit',
                ],
                [
                    'name' => 'options[map_coords_random_radius]',
                    'id' => 'map_coords_random_radius',
                    'type' => 'text',
                    'label' => 'Random Coordinates Radius(m)',
                    'placeholder' => 'Random Coordinates Radius(m)',
                    'default' => '500',
                ],
                [
                    'name' => 'map_cluster_settings',
                    'type' => 'title',
                    'label' => 'Map Cluster Settings',
                ],
                [
                    'name' => 'options[map_cluster]',
                    'id' => 'map_cluster',
                    'type' => 'select',
                    'label' => 'Enable Cluster',
                    'placeholder' => 'Enable Cluster',
                    'options' => [
                        'no' => 'No',
                        'yes' => 'Yes',
                    ],
                    'default' => 'yes',
                ],
                [
                    'name' => 'map_circle_settings',
                    'type' => 'title',
                    'label' => 'Map Circle Settings',
                ],
                [
                    'name' => 'options[map_circle]',
                    'id' => 'map_circle',
                    'type' => 'select',
                    'label' => 'Enable Circle',
                    'placeholder' => 'Enable Circle',
                    'options' => [
                        'no' => 'No',
                        'yes' => 'Yes',
                    ],
                    'default' => 'yes',
                ],
                [
                    'name' => 'options[map_circle_color]',
                    'id' => 'map_circle_color',
                    'type' => 'color-picker',
                    'label' => 'Color',
                    'placeholder' => 'Color',
                    'default' => '#000000',
                ],
                [
                    'name' => 'options[map_circle_fill_color]',
                    'id' => 'map_circle_fill_color',
                    'type' => 'color-picker',
                    'label' => 'Fill Color',
                    'placeholder' => 'Fill Color',
                    'default' => '#000000',
                ],
                [
                    'name' => 'options[map_circle_opacity]',
                    'id' => 'map_circle_opacity',
                    'type' => 'text',
                    'label' => 'Opacity',
                    'placeholder' => 'Opacity',
                    'default' => '0.5',
                ],
                [
                    'name' => 'options[map_circle_radius]',
                    'id' => 'map_circle_radius',
                    'type' => 'text',
                    'label' => 'Radius(m)',
                    'placeholder' => 'Radius(m)',
                    'default' => '1000',
                ],
            ],
        ],
    ],
    'integrations' => [
        [
            'section_title' => 'Google Maps',
            'section_description' => 'Complete the fields below',
            'fields' => [
                [
                    'name' => 'options[integrations_google_maps_enabled]',
                    'id' => 'integrations_google_maps_enabled',
                    'type' => 'checkbox',
                    'label' => 'Google Maps',
                ],
                [
                    'name' => 'options[integrations_google_maps]',
                    'id' => 'integrations_google_maps',
                    'type' => 'text',
                    'label' => 'Google Maps API Key',
                ],
            ],
        ],
        [
            'section_title' => 'Google Translate',
            'section_description' => 'Enable google translate for this site',
            'fields' => [
                [
                    'name' => 'options[google_translate_enabled]',
                    'id' => 'google_translate_enabled',
                    'type' => 'checkbox',
                    'label' => 'Google Translate',
                ],
                [
                    'name' => 'options[google_lang_default_lang]',
                    'id' => 'google_lang_default_lang',
                    'type' => 'select',
                    'label' => 'Default Language',
                    'options' => \App\Utils\Config::getList('sites', 'google_translate_options'),
                    'default' => 'en',
                ],
                [
                    'name' => 'options[google_lang_shape]',
                    'id' => 'google_lang_shape',
                    'type' => 'select',
                    'label' => 'Flag Shape',
                    'options' => [
                        'rectangle' => 'Rectangle',
                        'circle' => 'Circle',
                    ],
                    'default' => 'rectangle',
                ],
                [
                    'name' => 'options[google_lang_choices]',
                    'id' => 'google_lang_choices',
                    'type' => 'multi-checkbox',
                    'group_width' => 'full',
                    'label' => 'Languages',
                    'options' => \App\Utils\Config::getList('sites', 'google_translate_options'),
                ],
            ],
        ],
        [
            'section_title' => 'Google ReCaptcha V3',
            'section_description' => 'If the GDPR integration is enabled the system will load this integration after the user accepts the 3rd party cookies else it will load it during page load.',
            'fields' => [
                [
                    'name' => 'options[google_recaptcha_v3_enabled]',
                    'id' => 'google_recaptcha_v3_enabled',
                    'type' => 'checkbox',
                    'label' => 'Google ReCaptcha V3',
                ],
                [
                    'name' => 'options[google_recaptcha_v3_site_key]',
                    'id' => 'google_recaptcha_v3_site_key',
                    'type' => 'text',
                    'label' => 'Site Key',
                ],
                [
                    'name' => 'options[google_recaptcha_v3_secret_key]',
                    'id' => 'google_recaptcha_v3_secret_key',
                    'type' => 'text',
                    'label' => 'Secret Key',
                ],
            ],
        ],
        [
            'section_title' => 'Google Analytics',
            'section_description' => 'If the GDPR integration is enabled the system will load this integration after the user accepts the 3rd party cookies else it will load it during page load.',
            'fields' => [
                [
                    'name' => 'options[google_analytics_enabled]',
                    'id' => 'google_analytics_enabled',
                    'type' => 'checkbox',
                    'label' => 'Google Analytics 4',
                ],
                [
                    'name' => 'options[google_analytics_id]',
                    'id' => 'google_analytics_id',
                    'type' => 'text',
                    'label' => 'MEASUREMENT ID',
                    'placeholder' => 'G-##########',
                ],
            ],
        ],
        [
            'section_title' => 'Google Tag Manager',
            'section_description' => 'If the GDPR integration is enabled the system will load this integration after the user accepts the 3rd party cookies else it will load it during page load.',
            'fields' => [
                [
                    'name' => 'options[google_tag_manager_enabled]',
                    'id' => 'google_tag_manager_enabled',
                    'type' => 'checkbox',
                    'label' => 'Google Tag Manager',
                ],
                [
                    'name' => 'options[google_tag_manager_id]',
                    'id' => 'google_tag_manager_id',
                    'type' => 'text',
                    'label' => 'Google Tag Manager ID',
                    'placeholder' => 'GTM-#######',
                ],
            ],
        ],
        [
            'section_title' => 'GDPR consent',
            'section_description' => 'GDPR consent options',
            'fields' => [
                [
                    'name' => 'options[gdpr_enabled]',
                    'id' => 'gdpr_enabled',
                    'type' => 'checkbox',
                    'label' => 'GDPR',
                ],
                [
                    'type' => 'title',
                    'label' => 'Consent Popup',
                    'description' => '',
                ],
                [
                    'name' => 'options[gdpr_popup_title]',
                    'id' => 'gdpr_popup_title',
                    'type' => 'simple-html-editor',
                    'label' => 'Popup Title',
                    'group_width' => 'full',
                    'default' => '',
                ],
                [
                    'name' => 'options[gdpr_popup_message]',
                    'id' => 'gdpr_popup_message',
                    'type' => 'simple-html-editor',
                    'label' => 'Popup Description',
                    'group_width' => 'full',
                    'default' => '<p style="text-align: center;">We are using cookies to give you the best experience on our website. You can find out more about which cookies we are using or switch them off in settings</p>',
                ],
                [
                    'name' => 'options[gdpr_accept_btn_label]',
                    'id' => 'gdpr_accept_btn_label',
                    'type' => 'text',
                    'label' => 'Accept Button Label',
                    'default' => 'Accept',
                ],
                [
                    'name' => 'options[gdpr_declined_btn_label]',
                    'id' => 'gdpr_declined_btn_label',
                    'type' => 'text',
                    'label' => 'Declined Button Label',
                    'default' => '',
                ],
                [
                    'name' => 'options[gdpr_settings_btn_label]',
                    'id' => 'gdpr_settings_btn_label',
                    'type' => 'text',
                    'label' => 'Settings Label',
                    'default' => 'Settings',
                ],
                [
                    'type' => 'title',
                    'label' => 'Floating Button',
                    'description' => '',
                ],
                [
                    'name' => 'options[gdpr_floating_btn_label]',
                    'id' => 'gdpr_floating_btn_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Change cookie settings',
                ],
                [
                    'type' => 'title',
                    'label' => 'Settings',
                    'description' => '',
                ],
                [
                    'name' => 'options[gdpr_settings_description_title]',
                    'id' => 'gdpr_settings_description_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Description - Title',
                    'default' => 'Privacy Overview',
                ],
                [
                    'name' => 'options[gdpr_settings_description]',
                    'id' => 'gdpr_settings_description',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => 'Description - Content',
                    'default' => 'This website uses cookies so that we can provide you with the best user experience possible. Cookie information is stored in your browser and performs functions such as recognising you when you return to our website and helping our team to understand which sections of the website you find most interesting and useful.',
                    'description' => 'This will be visible when someone clicks the settings button.',
                ],
                [
                    'name' => 'options[gdpr_strictly_necessary_title]',
                    'id' => 'gdpr_strictly_necessary_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Strictly Necessary Cookies - Title',
                    'default' => 'Strictly Necessary Cookies',
                ],
                [
                    'name' => 'options[gdpr_strictly_necessary]',
                    'id' => 'gdpr_strictly_necessary',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => 'Strictly Necessary Cookies - Content',
                    'default' => 'Strictly Necessary Cookie should be enabled at all times so that we can save your preferences for cookie settings.',
                    'description' => 'The strickly necessary cookies will always be enabled',
                ],
                [
                    'name' => 'options[gdpr_3rd_party_cookies_title]',
                    'id' => 'gdpr_3rd_party_cookies_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => '3rd Party Cookies - Title',
                    'default' => '3rd Party Cookies',
                ],
                [
                    'name' => 'options[gdpr_3rd_party_cookies]',
                    'id' => 'gdpr_3rd_party_cookies',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => '3rd Party Cookies - Content',
                    'default' => 'This website uses Google Analytics to collect anonymous information such as the number of visitors to the site, and the most popular pages. Keeping this cookie enabled helps us to improve our website.',
                    'description' => 'The google analytics/google tag manager and google Recaptcha scripts will be included only when the customer accepts the 3rd party cookies',
                ],
                [
                    'name' => 'options[gdpr_cookies_policy_title]',
                    'id' => 'gdpr_cookies_policy_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Cookie Policy - Title',
                    'default' => 'Cookie Policy',
                ],
                [
                    'name' => 'options[gdpr_cookies_policy]',
                    'id' => 'gdpr_cookies_policy',
                    'type' => 'normal-html-editor',
                    'group_width' => 'full',
                    'label' => 'Cookie Policy - Content',
                    'default' => 'More information about our <a href="/cookie-policy">Cookie Policy</a>',
                ],
                [
                    'name' => 'options[gdpr_settings_accept_btn_label]',
                    'id' => 'gdpr_settings_accept_btn_label',
                    'type' => 'text',
                    'label' => 'Accept button Label',
                    'default' => 'Accept All',
                    'description' => 'This button is visible when the customer opens the gdpr settings. It will enable all the options when the visitor clicks it',
                ],
                [
                    'name' => 'options[gdpr_settings_save_btn_label]',
                    'id' => 'gdpr_settings_save_btn_label',
                    'type' => 'text',
                    'label' => 'Save button Label',
                    'default' => 'Save Settings',
                    'description' => 'This button is visible when the customer opens the gdpr settings. It will save only the options that are enabled from the visitor.',
                ],
            ],
        ],
        [
            'section_title' => 'SEO',
            'section_description' => 'Search Engine Optimization settings',
            'fields' => [
                [
                    'name' => 'options[robots_txt_enabled]',
                    'id' => 'robots_txt_enabled',
                    'type' => 'checkbox',
                    'label' => 'Robots.txt',
                ],
                [
                    'type' => 'title',
                    'label' => 'Robots.txt Content',
                    'description' => '',
                ],
                [
                    'name' => 'options[robots_txt]',
                    'id' => 'robots_txt',
                    'type' => 'textarea',
                    'group_width' => 'full',
                    'label' => 'Robots.txt Content',
                    'default' => "User-agent: *\nDisallow: /admin/\nDisallow: /files/\nSitemap: ",
                    'description' => 'Enter the content for your robots.txt file. This will be served at /robots.txt',
                ],
            ],
        ],
    ],
    'domain' => [
        [
            'section_title' => 'Domain & Test URL',
            'section_description' => 'Finalize your website\'s domain settings',
            'fields' => [
                [
                    'name' => 'host',
                    'type' => 'text',
                    'label' => 'Primary Domain',
                ],
                [
                    'name' => 'alias_host',
                    'type' => 'text',
                    'label' => 'Alias Domain',
                ],
            ],
        ],
        [
            'section_title' => 'Domain & Test URL',
            'section_description' => 'Finalize your website\'s domain settings',
            'columns' => 1,
            'fields' => [
                [
                    'name' => 'dummy',
                    'type' => 'content',
                    'class' => 'btn btn-pill btn-primary btn-validate-domain',
                    'description' => 'If you purchases a domain from a third-party provider (like GoDaddy, HostGator or 1&1) and want to keep it registered with them, you can connect it to your site by following a setup process called DNS Connect or domain mapping. <b>Please point your `@` and `www` records to the Qoetix IP address: {server_ip}.</b> Once you have done this, your domain should take some time propagate. You can check if your domain is pointing to the correct URL below:',
                    'label' => 'Validate your Domain',
                ],
            ],
        ],
    ],
];
