<?php
declare(strict_types=1);

$options = [
    'appearance' => [
        [
            'section_title' => 'Appearance',
            'section_description' => 'Style & personalize your site',
            'fields' => [
                [
                    'name' => 'options[style_primary_color]',
                    'id' => 'style_primary_color',
                    'type' => 'color-picker',
                    'label' => 'Site Primary Color',
                    'default' => '#FF4D00',
                ],
                [
                    'name' => 'options[style_secondary_color]',
                    'id' => 'style_secondary_color',
                    'type' => 'color-picker',
                    'label' => 'Site Secondary Color',
                    'default' => '#FFFFFF',
                ],
                [
                    'name' => 'logo',
                    'type' => 'file',
                    'label' => 'Menu logo',
                ],
                [
                    'name' => 'options[favicon]',
                    'id' => 'favicon',
                    'type' => 'file',
                    'label' => 'Favicon',
                ],
            ],
        ],
        [
            'section_title' => 'Blog/Product Labels',
            'section_description' => 'Button labels for the blog/product pages',
            'fields' => [
                [
                    'name' => 'options[previous_btn_label]',
                    'id' => 'previous_btn_label',
                    'type' => 'text',
                    'label' => 'Previous Button Label',
                    'default' => 'Προηγούμενο',
                ],
                [
                    'name' => 'options[next_btn_label]',
                    'id' => 'next_btn_label',
                    'type' => 'text',
                    'label' => 'Next Button Label',
                    'default' => 'Επόμενο',
                ],
                [
                    'name' => 'options[more_btn_label]',
                    'id' => 'more_btn_label',
                    'type' => 'text',
                    'label' => 'More Button Label',
                    'default' => 'Μάθε Περισσότερα…',
                ],
                [
                    'name' => 'options[no_results_label]',
                    'id' => 'no_results_label',
                    'type' => 'text',
                    'label' => 'No Results Label',
                    'default' => 'Δεν βρέθηκαν αποτελέσματα!',
                ],
            ],
        ],
        [
            'section_title' => 'Map',
            'section_description' => 'Style the map pins',
            'fields' => [
                [
                    'name' => 'options[map_marker]',
                    'id' => 'map_marker',
                    'type' => 'file',
                    'label' => 'Pin',
                ],
                [
                    'name' => 'options[map_marker_active]',
                    'id' => 'map_marker_active',
                    'type' => 'file',
                    'label' => 'Pin when active',
                ],
                [
                    'name' => 'options[map_marker_width]',
                    'id' => 'map_marker_width',
                    'type' => 'text',
                    'label' => 'Pin width (px)',
                    'default' => '30',
                ],
                [
                    'name' => 'options[map_marker_height]',
                    'id' => 'map_marker_height',
                    'type' => 'text',
                    'label' => 'Pin height (px)',
                    'default' => '55',
                ],
            ],
        ],
    ],
    'integrations' => [
        [
            'section_title' => 'Google Maps',
            'section_description' => 'Complete the fields below',
            'fields' => [
                [
                    'name' => 'options[integrations_google_maps_enabled]',
                    'id' => 'integrations_google_maps_enabled',
                    'type' => 'checkbox',
                    'label' => 'Google Maps',
                ],
                [
                    'name' => 'options[integrations_google_maps]',
                    'id' => 'integrations_google_maps',
                    'type' => 'text',
                    'label' => 'Google Maps API Key',
                ],
            ],
        ],
        [
            'section_title' => 'Google Translate',
            'section_description' => 'Enable google translate for this site',
            'fields' => [
                [
                    'name' => 'options[google_translate_enabled]',
                    'id' => 'google_translate_enabled',
                    'type' => 'checkbox',
                    'label' => 'Google Translate',
                ],
                [
                    'name' => 'options[google_lang_default_lang]',
                    'id' => 'google_lang_default_lang',
                    'type' => 'select',
                    'label' => 'Default Language',
                    'options' => \App\Utils\Config::getList('sites', 'google_translate_options'),
                    'default' => 'en',
                ],
                [
                    'name' => 'options[google_lang_shape]',
                    'id' => 'google_lang_shape',
                    'type' => 'select',
                    'label' => 'Flag Shape',
                    'options' => [
                        'rectangle' => 'Rectangle',
                        'circle' => 'Circle',
                    ],
                    'default' => 'rectangle',
                ],
                [
                    'name' => 'options[google_lang_choices]',
                    'id' => 'google_lang_choices',
                    'type' => 'multi-checkbox',
                    'group_width' => 'full',
                    'label' => 'Languages',
                    'options' => \App\Utils\Config::getList('sites', 'google_translate_options'),
                ],
            ],
        ],
        [
            'section_title' => 'Google ReCaptcha V3',
            'section_description' => 'If the GDPR integration is enabled the system will load this integration after the user accepts the 3rd party cookies else it will load it during page load.',
            'fields' => [
                [
                    'name' => 'options[google_recaptcha_v3_enabled]',
                    'id' => 'google_recaptcha_v3_enabled',
                    'type' => 'checkbox',
                    'label' => 'Google ReCaptcha V3',
                ],
                [
                    'name' => 'options[google_recaptcha_v3_site_key]',
                    'id' => 'google_recaptcha_v3_site_key',
                    'type' => 'text',
                    'label' => 'Site Key',
                ],
                [
                    'name' => 'options[google_recaptcha_v3_secret_key]',
                    'id' => 'google_recaptcha_v3_secret_key',
                    'type' => 'text',
                    'label' => 'Secret Key',
                ],
            ],
        ],
        [
            'section_title' => 'Google Analytics',
            'section_description' => 'If the GDPR integration is enabled the system will load this integration after the user accepts the 3rd party cookies else it will load it during page load.',
            'fields' => [
                [
                    'name' => 'options[google_analytics_enabled]',
                    'id' => 'google_analytics_enabled',
                    'type' => 'checkbox',
                    'label' => 'Google Analytics 4',
                ],
                [
                    'name' => 'options[google_analytics_id]',
                    'id' => 'google_analytics_id',
                    'type' => 'text',
                    'label' => 'MEASUREMENT ID',
                    'placeholder' => 'G-##########',
                ],
            ],
        ],
        [
            'section_title' => 'Google Tag Manager',
            'section_description' => 'If the GDPR integration is enabled the system will load this integration after the user accepts the 3rd party cookies else it will load it during page load.',
            'fields' => [
                [
                    'name' => 'options[google_tag_manager_enabled]',
                    'id' => 'google_tag_manager_enabled',
                    'type' => 'checkbox',
                    'label' => 'Google Tag Manager',
                ],
                [
                    'name' => 'options[google_tag_manager_id]',
                    'id' => 'google_tag_manager_id',
                    'type' => 'text',
                    'label' => 'Google Tag Manager ID',
                    'placeholder' => 'GTM-#######',
                ],
            ],
        ],
        [
            'section_title' => 'GDPR consent',
            'section_description' => 'GDPR consent options',
            'fields' => [
                [
                    'name' => 'options[gdpr_enabled]',
                    'id' => 'gdpr_enabled',
                    'type' => 'checkbox',
                    'label' => 'GDPR',
                ],
                [
                    'type' => 'title',
                    'label' => 'Consent Popup',
                    'description' => '',
                ],
                [
                    'name' => 'options[gdpr_popup_message]',
                    'id' => 'gdpr_popup_message',
                    'type' => 'simple-html-editor',
                    'label' => 'Popup Description',
                    'group_width' => 'full',
                    'default' => '<p style="text-align: center;">Χρησιμοποιούμε cookies για να σας προσφέρουμε την καλύτερη εμπειρία στον ιστότοπό μας. Μπορείτε να μάθετε περισσότερα σχετικά με τα cookies που χρησιμοποιούμε ή να τα απενεργοποιήσετε στις ρυθμίσεις</p>',
                ],
                [
                    'name' => 'options[gdpr_accept_btn_label]',
                    'id' => 'gdpr_accept_btn_label',
                    'type' => 'text',
                    'label' => 'Accept Button Label',
                    'default' => 'Αποδέχομαι',
                ],
                [
                    'name' => 'options[gdpr_settings_btn_label]',
                    'id' => 'gdpr_settings_btn_label',
                    'type' => 'text',
                    'label' => 'Settings Button Label',
                    'default' => 'Ρυθμίσεις',
                ],
                [
                    'type' => 'title',
                    'label' => 'Floating Button',
                    'description' => '',
                ],
                [
                    'name' => 'options[gdpr_floating_btn_label]',
                    'id' => 'gdpr_floating_btn_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Αλλάξτε τις ρυθμίσεις των cookie',
                ],
                [
                    'type' => 'title',
                    'label' => 'Settings',
                    'description' => '',
                ],
                [
                    'name' => 'options[gdpr_settings_description_title]',
                    'id' => 'gdpr_settings_description_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Description - Title',
                    'default' => 'Privacy Overview',
                ],
                [
                    'name' => 'options[gdpr_settings_description]',
                    'id' => 'gdpr_settings_description',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => 'Description - Content',
                    'default' => 'Αυτός ο ιστότοπος χρησιμοποιεί cookies ώστε να μπορούμε να σας παρέχουμε την καλύτερη δυνατή εμπειρία χρήστη. Οι πληροφορίες των cookie αποθηκεύονται στο πρόγραμμα περιήγησής σας και εκτελούν λειτουργίες όπως η αναγνώριση σας όταν επιστρέφετε στον ιστότοπό μας και βοηθά την ομάδα μας να κατανοήσει ποιες ενότητες του ιστότοπου θεωρείτε πιο ενδιαφέρουσες και χρήσιμες.',
                    'description' => 'This will be visible when someone clicks the settings button.',
                ],
                [
                    'name' => 'options[gdpr_strictly_necessary_title]',
                    'id' => 'gdpr_strictly_necessary_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Strictly Necessary Cookies - Title',
                    'default' => 'Strictly Necessary Cookies',
                ],
                [
                    'name' => 'options[gdpr_strictly_necessary]',
                    'id' => 'gdpr_strictly_necessary',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => 'Strictly Necessary Cookies - Content',
                    'default' => 'Το Strictly Necessary Cookies θα πρέπει να είναι ενεργοποιημένο ανά πάσα στιγμή, ώστε να μπορούμε να αποθηκεύσουμε τις προτιμήσεις σας για τις ρυθμίσεις των cookie.',
                    'description' => 'The strickly necessary cookies will always be enabled',
                ],
                [
                    'name' => 'options[gdpr_3rd_party_cookies_title]',
                    'id' => 'gdpr_3rd_party_cookies_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => '3rd Party Cookies - Title',
                    'default' => '3rd Party Cookies',
                ],
                [
                    'name' => 'options[gdpr_3rd_party_cookies]',
                    'id' => 'gdpr_3rd_party_cookies',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => '3rd Party Cookies - Content',
                    'default' => 'Αυτός ο ιστότοπος χρησιμοποιεί το Google Analytics για τη συλλογή ανώνυμων πληροφοριών, όπως τον αριθμό των επισκεπτών στον ιστότοπο και τις πιο δημοφιλείς σελίδες. Η διατήρηση αυτού του cookie ενεργοποιημένο μας βοηθά να βελτιώσουμε τον ιστότοπό μας.',
                    'description' => 'The google analytics/google tag manager and google Recaptcha scripts will be included only when the customer accepts the 3rd party cookies',
                ],
                [
                    'name' => 'options[gdpr_cookies_policy_title]',
                    'id' => 'gdpr_cookies_policy_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Cookie Policy - Title',
                    'default' => 'Cookie Policy',
                ],
                [
                    'name' => 'options[gdpr_cookies_policy]',
                    'id' => 'gdpr_cookies_policy',
                    'type' => 'normal-html-editor',
                    'group_width' => 'full',
                    'label' => 'Cookie Policy - Content',
                    'default' => 'Περισσότερες πληροφορίες σχετικά με την Πολιτική μας για τα <a href="cookie-policy">cookies</a>',
                ],
                [
                    'name' => 'options[gdpr_settings_accept_btn_label]',
                    'id' => 'gdpr_settings_accept_btn_label',
                    'type' => 'text',
                    'label' => 'Accept button Label',
                    'default' => 'Αποδοχή όλων',
                    'description' => 'This button is visible when the customer opens the gdpr settings. It will enable all the options when the visitor clicks it',
                ],
                [
                    'name' => 'options[gdpr_settings_save_btn_label]',
                    'id' => 'gdpr_settings_save_btn_label',
                    'type' => 'text',
                    'label' => 'Save button Label',
                    'default' => 'Αποθήκευση ρυθμίσεων',
                    'description' => 'This button is visible when the customer opens the gdpr settings. It will save only the options that are enabled from the visitor.',
                ],
            ],
        ],
        [
            'section_title' => 'SEO',
            'section_description' => 'Search Engine Optimization settings',
            'fields' => [
                [
                    'name' => 'options[robots_txt_enabled]',
                    'id' => 'robots_txt_enabled',
                    'type' => 'checkbox',
                    'label' => 'Robots.txt',
                ],
                [
                    'type' => 'title',
                    'label' => 'Robots.txt Content',
                    'description' => '',
                ],
                [
                    'name' => 'options[robots_txt]',
                    'id' => 'robots_txt',
                    'type' => 'textarea',
                    'group_width' => 'full',
                    'label' => 'Robots.txt Content',
                    'default' => "User-agent: *\nDisallow: /admin/\nDisallow: /files/\nSitemap: ",
                    'description' => 'Enter the content for your robots.txt file. This will be served at /robots.txt',
                ],
            ],
        ],
    ],
];
