<?php

declare(strict_types=1);

$options = [
    'home' => [
        [
            'section_title' => 'Hero Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
                [
                    'name' => 'options[hero_sub_title]',
                    'id' => 'hero_sub_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Welcome to Nea Imóveis',
                ],
                [
                    'name' => 'options[hero_title]',
                    'id' => 'hero_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Your Gateway to Exceptional Real Estate Opportunities',
                ],
            ],
        ],
        [
            'section_title' => 'Featured Properties Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[featured_sub_title]',
                    'id' => 'featured_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Featured Properties',
                ],
                [
                    'name' => 'options[featured_title]',
                    'id' => 'featured_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Discover Your Dream Home or Investment Opportunity',
                ],
                [
                    'name' => 'options[featured_description]',
                    'id' => 'featured_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => 'Explore some of the most sought-after properties from our curated portfolio.',
                ],
                [
                    'name' => 'options[featured_button_label]',
                    'id' => 'featured_button_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'View All Properties',
                ],
            ],
        ],
        [
            'section_title' => 'Locations Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[locations_sub_title]',
                    'id' => 'locations_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Locations',
                ],
                [
                    'name' => 'options[locations_title]',
                    'id' => 'locations_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Discover Properties in These Prime Areas',
                ],
                [
                    'name' => 'options[locations_description]',
                    'id' => 'locations_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => 'Explore some of the most sought-after locations we serve. Click on a location to browse all available properties!',
                ],
                [
                    'name' => 'location_list',
                    'type' => 'array',
                    'label' => 'Location List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[location_list][location_image]',
                            'id' => 'location_image',
                            'type' => 'file',
                            'label' => 'Image',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[location_list][location_district]',
                            'id' => 'location_district',
                            'type' => 'select',
                            'enable_search' => true,
                            'label' => 'District',
                            'options' => \App\Connector\Reports::propertyDistrictDropdownList(),
                        ],
                        [
                            'name' => 'options[location_list][location_btn_label]',
                            'id' => 'location_btn_label',
                            'type' => 'text',
                            'label' => 'Button Label',
                            'default' => 'Label',
                        ],
                    ],
                    'display_fields' => [
                        'location_district' => 'Title',
                    ],
                ],
                [
                    'name' => 'options[locations_button_label]',
                    'id' => 'locations_button_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'View All Locations',
                ],
            ],
        ],
        [
            'section_title' => 'Partners Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[partners_sub_title]',
                    'id' => 'partners_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Our Partners',
                ],
                [
                    'name' => 'options[partners_title]',
                    'id' => 'partners_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Trusted Collaborators in Real Estate',
                ],
                [
                    'name' => 'options[partners_description]',
                    'id' => 'partners_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => 'We are proud to work with industry-leading partners who help us deliver exceptional services and opportunities to our clients.',
                ],
                [
                    'name' => 'partners_list',
                    'type' => 'array',
                    'label' => 'Partners List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[partners_list][partners_image]',
                            'id' => 'partners_image',
                            'type' => 'file',
                            'label' => 'Image',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[partners_list][partners_title]',
                            'id' => 'partners_title',
                            'type' => 'text',
                            'label' => 'Title',
                            'default' => '',
                        ],
                    ],
                    'display_fields' => [
                        'partners_title' => 'Title',
                    ],
                ],
                [
                    'name' => 'options[partners_button_label]',
                    'id' => 'partners_button_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Our Partners',
                ],
            ],
        ],
        [
            'section_title' => 'Explore Properties',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[explore_sub_title]',
                    'id' => 'explore_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Locations',
                ],
                [
                    'name' => 'options[explore_title]',
                    'id' => 'explore_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Explore More Properties',
                ],
                [
                    'name' => 'options[explore_description]',
                    'id' => 'explore_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => 'Check out some of the most desirable areas we cover. Click on a location to view all available properties.',
                ],
            ],
        ],
    ],
    'about' => [
        [
            'section_title' => 'Hero Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_sub_title]',
                    'id' => 'hero_sub_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'About Nea Imóveis',
                ],
                [
                    'name' => 'options[hero_title]',
                    'id' => 'hero_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Passionate About Real Estate, Committed to you',
                ],
            ],
        ],
        [
            'section_title' => 'Our Service',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[ourservice_sub_title]',
                    'id' => 'ourservice_sub_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Our Services',
                ],
                [
                    'name' => 'options[ourservice_title]',
                    'id' => 'ourservice_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Personalized to Meet Your Unique Real Estate Needs',
                ],
                [
                    'name' => 'options[ourservice_description]',
                    'id' => 'ourservice_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => '<p>At Nea Imóveis, real estate is more than just business—it’s our passion. Since our founding in 2020, we have been dedicated to helping clients find high-quality properties, make smart investments, and navigate the real estate market with confidence. Whether you’re looking for a dream home, a profitable investment, or professional property management, we are here to provide personalized service every step of the way.</p><br/><p>Our mission is simple: to connect people with the right properties while building lasting relationships based on trust, integrity, and expertise. We don’t just sell real estate—we help you create a better future.</p>',
                ],
                [
                    'name' => 'options[gallery_column_one]',
                    'id' => 'gallery_column_one',
                    'group_width' => 'full',
                    'type' => 'file',
                    'label' => 'Gallery - First Column',
                    'default' => '',
                ],
                [
                    'name' => 'options[gallery_column_two_a]',
                    'id' => 'gallery_column_two_a',
                    'type' => 'file',
                    'label' => 'Gallery - Second Column - First Image',
                    'default' => '',
                ],
                [
                    'name' => 'options[gallery_column_two_b]',
                    'id' => 'gallery_column_two_b',
                    'type' => 'file',
                    'label' => 'Gallery - Second Column - Last Image',
                    'default' => '',
                ],
                [
                    'name' => 'options[gallery_column_three]',
                    'id' => 'gallery_column_three',
                    'group_width' => 'full',
                    'type' => 'file',
                    'label' => 'Gallery - Third Column',
                    'default' => '',
                ],
                [
                    'name' => 'options[gallery_column_four_a]',
                    'id' => 'gallery_column_four_a',
                    'type' => 'file',
                    'label' => 'Gallery - Fourth Column - First Image',
                    'default' => '',
                ],
                [
                    'name' => 'options[gallery_column_four_b]',
                    'id' => 'gallery_column_four_b',
                    'type' => 'file',
                    'label' => 'Gallery - Fourth Column - Last Image',
                    'default' => '',
                ],
                [
                    'name' => 'options[gallery_column_five]',
                    'id' => 'gallery_column_five',
                    'group_width' => 'full',
                    'type' => 'file',
                    'label' => 'Gallery - Fifth Column',
                    'default' => '',
                ],
            ],
        ],
        [
            'section_title' => 'Why Choose Us Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[whyus_sub_title]',
                    'id' => 'whyus_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Why Choose Us',
                ],
                [
                    'name' => 'options[whyus_title]',
                    'id' => 'whyus_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Your Trusted Partner in Real Estate',
                ],
                [
                    'name' => 'options[whyus_description]',
                    'id' => 'whyus_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => 'Choosing the right real estate agency makes all the difference. At Nea Imóveis, we go beyond transactions—we build relationships.',
                ],
                [
                    'name' => 'whyus_list',
                    'type' => 'array',
                    'label' => 'Why Choose Us List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[whyus_list][whyus_image]',
                            'id' => 'whyus_image',
                            'type' => 'file',
                            'label' => 'Image',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[whyus_list][whyus_title]',
                            'id' => 'whyus_title',
                            'type' => 'text',
                            'label' => 'Title',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[whyus_list][whyus_details]',
                            'id' => 'whyus_details',
                            'type' => 'text',
                            'label' => 'Details',
                            'default' => '',
                        ],
                    ],
                    'display_fields' => [
                        'whyus_title' => 'Title',
                    ],
                ],
            ],
        ],
    ],
    'contact' => [
        [
            'section_title' => 'Hero Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_sub_title]',
                    'id' => 'hero_sub_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Contact Us',
                ],
                [
                    'name' => 'options[hero_title]',
                    'id' => 'hero_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Let’s Find Your Perfect Property Together',
                ],
            ],
        ],
        [
            'section_title' => 'Get in Touch',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[getintouch_title]',
                    'id' => 'getintouch_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Get in Touch',
                ],
                [
                    'name' => 'options[getintouch_description]',
                    'id' => 'getintouch_description',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Whether you’re looking to buy, rent, invest, or need expert property management, our team is ready to assist you. Reach out today, and let’s turn your real estate goals into reality!',
                ],
                [
                    'name' => 'options[getintouch_email_title]',
                    'id' => 'getintouch_email_title',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email',
                ],
                [
                    'name' => 'options[getintouch_email_icon]',
                    'id' => 'getintouch_email_icon',
                    'type' => 'file',
                    'label' => 'Email Icon',
                    'default' => '',
                ],
                [
                    'name' => 'options[getintouch_call_title]',
                    'id' => 'getintouch_call_title',
                    'type' => 'text',
                    'label' => 'Phone Label',
                    'default' => 'Phone',
                ],
                [
                    'name' => 'options[getintouch_call_icon]',
                    'id' => 'getintouch_call_icon',
                    'type' => 'file',
                    'label' => 'Phone Icon',
                    'default' => '',
                ],
                [
                    'name' => 'options[getintouch_whatsapp_title]',
                    'id' => 'getintouch_whatsapp_title',
                    'type' => 'text',
                    'label' => 'Whatsapp Label',
                    'default' => 'Whatsapp',
                ],
                [
                    'name' => 'options[getintouch_whatsapp_icon]',
                    'id' => 'getintouch_whatsapp_icon',
                    'type' => 'file',
                    'label' => 'Whatsapp Icon',
                    'default' => '',
                ],
                [
                    'name' => 'options[getintouch_address_title]',
                    'id' => 'getintouch_address_title',
                    'type' => 'text',
                    'label' => 'Address Label',
                    'default' => 'Address',
                ],
                [
                    'name' => 'options[getintouch_address_icon]',
                    'id' => 'getintouch_address_icon',
                    'type' => 'file',
                    'label' => 'Address Icon',
                    'default' => '',
                ],
            ],
        ],
        [
            'section_title' => 'Contact Form Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_form_title]',
                    'id' => 'contact_form_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Send Us a Message',
                ],
                [
                    'name' => 'options[contact_form_sub_title]',
                    'id' => 'contact_form_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Have a question? Fill out the form below, and our team will get back to you as soon as possible.',
                ],
                [
                    'name' => 'options[contact_form_name]',
                    'id' => 'contact_form_name',
                    'type' => 'text',
                    'label' => 'Full Name Label',
                    'default' => 'Full Name*',
                ],
                [
                    'name' => 'options[contact_form_email]',
                    'id' => 'contact_form_email',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email*',
                ],
                [
                    'name' => 'options[contact_form_phone]',
                    'id' => 'contact_form_phone',
                    'type' => 'text',
                    'label' => 'Phone Label',
                    'default' => 'Phone',
                ],
                [
                    'name' => 'options[contact_form_message]',
                    'id' => 'contact_form_message',
                    'type' => 'text',
                    'label' => 'Message Label',
                    'default' => 'Message',
                ],
                [
                    'name' => 'options[contact_form_disclaimer]',
                    'id' => 'contact_form_disclaimer',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Disclaimer',
                    'default' => 'By submitting this form you confirm that this website can store your submitted information, agree to our <a href="/privacy-policy">privacy policy</a> and consent to <a href="/cookies-policy">cookies</a> being stored on your computer.',
                ],
                [
                    'name' => 'options[contact_form_btn]',
                    'id' => 'contact_form_btn',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Submit',
                ],
            ],
        ],
    ],
    'propertieslisting' => [
        [
            'section_title' => 'Properties Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[properties_title]',
                    'id' => 'properties_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Available Properties',
                ],
            ],
        ],
    ],
    'property' => [
        [
            'section_title' => 'Property Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[description_title]',
                    'id' => 'description_title',
                    'type' => 'text',
                    'label' => 'Description label',
                    'default' => 'Description',
                ],
                [
                    'name' => 'options[location_title]',
                    'id' => 'location_title',
                    'type' => 'text',
                    'label' => 'Location label',
                    'default' => 'Location',
                ],
                [
                    'name' => 'options[location_details]',
                    'id' => 'location_details',
                    'type' => 'text',
                    'label' => 'Location details label',
                    'group_width' => 'full',
                    'default' => 'This property is located in a prime area with easy access to essential amenities and services. Situated in a well-established neighborhood, it offers a perfect blend of convenience and tranquility.',
                ],
                [
                    'name' => 'options[agent_email_icon]',
                    'id' => 'agent_email_icon',
                    'type' => 'file',
                    'label' => 'Agent email icon',
                ],
                [
                    'name' => 'options[agent_call_icon]',
                    'id' => 'agent_call_icon',
                    'type' => 'file',
                    'label' => 'Agent call icon',
                ],
            ],
        ],
        [
            'section_title' => 'Similar Property Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[similar_properties_sub_title]',
                    'id' => 'similar_properties_sub_title',
                    'type' => 'text',
                    'label' => 'Similar Property Sub Title',
                    'default' => 'Discover More',
                ],
                [
                    'name' => 'options[similar_properties_title]',
                    'id' => 'similar_properties_title',
                    'type' => 'text',
                    'label' => 'Similar Property Title',
                    'default' => 'Similar Properties',
                ],
            ],
        ],
        [
            'section_title' => 'Enquire Form',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_form_title]',
                    'id' => 'contact_form_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Enquire Now',
                ],
                [
                    'name' => 'options[contact_form_sub_title]',
                    'id' => 'contact_form_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'By submitting this form you confirm that this website can store your submitted information, agree to our privacy policy and consent to cookies being stored on your computer.',
                ],
                [
                    'name' => 'options[contact_first_name]',
                    'id' => 'contact_first_name',
                    'type' => 'text',
                    'label' => 'First Name Label',
                    'default' => 'First Name*',
                ],
                [
                    'name' => 'options[contact_last_name]',
                    'id' => 'contact_last_name',
                    'type' => 'text',
                    'label' => 'Last Name Label',
                    'default' => 'Last Name*',
                ],
                [
                    'name' => 'options[contact_form_email]',
                    'id' => 'contact_form_email',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email*',
                ],
                [
                    'name' => 'options[contact_form_phone]',
                    'id' => 'contact_form_phone',
                    'type' => 'text',
                    'label' => 'Phone Label',
                    'default' => 'Phone',
                ],
                [
                    'name' => 'options[contact_form_message]',
                    'id' => 'contact_form_message',
                    'type' => 'text',
                    'label' => 'Message Label',
                    'default' => 'Message',
                ],
                [
                    'name' => 'options[contact_form_disclaimer]',
                    'id' => 'contact_form_disclaimer',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Disclaimer',
                    'default' => 'By submitting this form you confirm that this website can store your submitted information, agree to our <a href="/privacy-policy">privacy policy</a> and consent to <a href="/cookies-policy">cookies</a> being stored on your computer.',
                ],
                [
                    'name' => 'options[contact_form_btn]',
                    'id' => 'contact_form_btn',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Submit',
                ],
            ],
        ],
    ],
    'pricing' => [
        [
            'section_title' => 'Hero Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_title]',
                    'id' => 'hero_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Pricing',
                ],
                [
                    'name' => 'options[hero_description]',
                    'id' => 'hero_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => 'Whether you’re an individual looking to list a few properties or an agency managing multiple listings, Nea Imóveis has the right plan for you. Explore our flexible options below.',
                ],
            ],
        ],
        [
            'section_title' => 'Basic Plan',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[basicPlan_title]',
                    'id' => 'basicPlan_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Basic Plans',
                ],
                [
                    'name' => 'options[basicPlan_sub_title]',
                    'id' => 'basicPlan_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'For Individual Sellers',
                ],
                [
                    'name' => 'options[basicPlan_description]',
                    'id' => 'basicPlan_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => '<p>✅ <strong>Includes</strong></p><ul><li>Publicação de até 15 anúncios ativos simultaneamente</li><li>Destaque na homepage (incluído nos planos trimestral, semestral e semanal)</li><li>Renovação de anúncios permitida (sem custo adicional)</li><li>Acesso a painel com estatísticas: número de visualizações por anúncio</li><li>Suporte dedicado via WhatsApp e Email</li><li>Inclusão nas campanhas de marketing digital (caso contratado o impulso)</li><li>Perfil personalizado para o anunciante</li><li>Anúncios indexados no Google e redes sociais</li></ul><p><b>📌 </b><strong>Monthly – 15,000 Kz</strong></p><ul><li>Up to 15 active listings</li><li>Statistics dashboard</li></ul><p><b>📌 </b><strong>Quarterly – 40,000 Kz</strong></p><ul><li>Everything from the monthly plan</li><li>1 featured listing per month</li></ul><p><b>📌 </b><strong>Semi-Annual – 75,000 Kz</strong></p><ul><li>Everything from the quarterly plan</li><li>Up to 2 featured listings</li><li>Automatic renewal</li></ul><p><b>💥 </b><strong>Add-Ons for Individuals</strong></p><ul><li>Additional featured listing: 3,000 Kz/week</li><li>Social media boost (Facebook, Instagram, TikTok): 15,000 Kz/7 days</li></ul>',
                ],
                [
                    'name' => 'options[basicPlan_cta_description]',
                    'id' => 'basicPlan_cta_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'CTA Description',
                    'default' => '<p><strong>🤖 Ative Seu Anúncio via Bot do WhatsApp – 2.000 Kz/semana</strong></p>',
                ],
                [
                    'name' => 'options[basicPlan_button_label]',
                    'id' => 'basicPlan_button_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Subscribe',
                ],
                [
                    'name' => 'options[basicPlan_button_link]',
                    'id' => 'basicPlan_button_link',
                    'type' => 'text',
                    'label' => 'Button Link',
                    'default' => 'https://jungl.ml/iUd16Q8',
                ],
            ],
        ],
        [
            'section_title' => 'Pro Plan',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[proPlan_title]',
                    'id' => 'proPlan_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Platina Pro Plan',
                ],
                [
                    'name' => 'options[proPlan_sub_title]',
                    'id' => 'proPlan_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'For Real Estate Agencies',
                ],
                [
                    'name' => 'options[proPlan_description]',
                    'id' => 'proPlan_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => '<p><b>✅ </b><strong>Includes</strong></p><ul><li>Unlimited listings</li><li>Up to 10 featured properties on the homepage</li><li>3 virtual tours per month</li><li>2 social media boosts per month</li><li>Dashboard with statistics + market insights</li><li>Monthly consultation with a NEA expert</li><li>Dedicated account manager</li><li>Guaranteed minimum of 15 leads/month</li></ul><p><b>💰 </b><strong>Pricing</strong></p><ul><li><b>Monthly:</b> 90,000 Kz</li><li><b>Quarterly:</b> 243,000 Kz (10% discount)</li><li><b>Annual:</b> 864,000 Kz (20% discount)</li></ul><p><b>💥 </b><strong>Add-Ons for Agencies</strong></p><ul><li>Additional virtual tour: <b>7,000 Kz</b></li><li>Extra social media boost: <b>15,000 Kz/week</b></li><li>Extra homepage feature: <b>4,000 Kz/week</b></li></ul>',
                ],
                [
                    'name' => 'options[proPlan_cta_description]',
                    'id' => 'proPlan_cta_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'CTA Description',
                    'default' => '<p><strong>🤖 Ative Seu Anúncio via Bot do WhatsApp – 1.000 Kz/semana</strong></p>',
                ],
                [
                    'name' => 'options[proPlan_button_label]',
                    'id' => 'proPlan_button_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Subscribe',
                ],
                [
                    'name' => 'options[proPlan_button_link]',
                    'id' => 'proPlan_button_link',
                    'type' => 'text',
                    'label' => 'Button Link',
                    'default' => 'https://jungl.ml/iUd16Q8',
                ],
            ],
        ],
    ],
    'listing' => [
        [
            'section_title' => 'Hero Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_title]',
                    'id' => 'hero_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Add Listing',
                ],
                [
                    'name' => 'options[hero_description]',
                    'id' => 'hero_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => 'Create an Account With Nea Imóveis to List Your Property With Us',
                ],
            ],
        ],
        [
            'section_title' => 'Account Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[account_title]',
                    'id' => 'account_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Already Have an Account?',
                ],
                [
                    'name' => 'options[account_description]',
                    'id' => 'account_description',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'If you already have an account, simply log in to access your dashboard and manage your listings.',
                ],
                [
                    'name' => 'options[account_button_label]',
                    'id' => 'account_button_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Log In Here',
                ],
                [
                    'name' => 'options[account_button_link]',
                    'id' => 'account_button_link',
                    'type' => 'text',
                    'label' => 'Button Link',
                    'default' => 'https://seller.nea-imoveis.com/',
                ],
            ],
        ],
        [
            'section_title' => 'Contact Form Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_form_title]',
                    'id' => 'contact_form_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'New to Nea Imóveis? Sign Up to Get Started',
                ],
                [
                    'name' => 'options[contact_form_sub_title]',
                    'id' => 'contact_form_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'If you don’t have an account yet, register below to create one and start listing your property today.',
                ],
                [
                    'name' => 'options[contact_form_first_name]',
                    'id' => 'contact_form_first_name',
                    'type' => 'text',
                    'label' => 'First Name Label',
                    'default' => 'First Name*',
                ],
                [
                    'name' => 'options[contact_form_last_name]',
                    'id' => 'contact_form_last_name',
                    'type' => 'text',
                    'label' => 'Last Name Label',
                    'default' => 'Last Name',
                ],
                [
                    'name' => 'options[contact_form_email]',
                    'id' => 'contact_form_email',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email*',
                ],
                [
                    'name' => 'options[contact_form_phone]',
                    'id' => 'contact_form_phone',
                    'type' => 'text',
                    'label' => 'Phone Label',
                    'default' => 'Phone',
                ],
                [
                    'name' => 'options[contact_form_message]',
                    'id' => 'contact_form_message',
                    'type' => 'text',
                    'label' => 'Message Label',
                    'default' => 'Message',
                ],
                [
                    'name' => 'options[contact_form_disclaimer]',
                    'id' => 'contact_form_disclaimer',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Disclaimer',
                    'default' => 'By submitting this form you agree to our <a href="/privacy-policy">privacy policy</a>.',
                ],
                [
                    'name' => 'options[contact_form_btn]',
                    'id' => 'contact_form_btn',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Sign Up',
                ],
            ],
        ],
    ],
    'services' => [
        [
            'section_title' => 'Hero Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_title]',
                    'id' => 'hero_title',
                    'group_width' => 'full',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Services',
                ],
                [
                    'name' => 'options[hero_description]',
                    'id' => 'hero_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => 'Tailored Real Estate Solutions for Every Need',
                ],
            ],
        ],
    ],
    'components/services' => [
        [
            'section_title' => 'Our Services',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[services_sub_title]',
                    'id' => 'services_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Our Services',
                ],
                [
                    'name' => 'options[services_title]',
                    'id' => 'services_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Personalized to Meet Your Unique Real Estate Needs',
                ],
                [
                    'name' => 'options[services_description]',
                    'id' => 'services_description',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => 'Let us turn your dreams into reality. Whether it\'s finding a cozy home or growing your capital, our dedicated and honest consultants are here to help.',
                ],
                [
                    'name' => 'options[services_button_label]',
                    'id' => 'services_button_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Our Services',
                ],
                [
                    'name' => 'services_list',
                    'type' => 'array',
                    'label' => 'Services List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[services_list][services_image]',
                            'id' => 'services_image',
                            'type' => 'file',
                            'label' => 'Image',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[services_list][services_title]',
                            'id' => 'services_title',
                            'type' => 'text',
                            'label' => 'Title',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[services_list][services_details]',
                            'id' => 'services_details',
                            'type' => 'text',
                            'label' => 'Details',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[services_list][services_description]',
                            'id' => 'services_description',
                            'type' => 'simple-html-editor',
                            'label' => 'Description',
                            'default' => '',
                        ],
                    ],
                    'display_fields' => [
                        'services_title' => 'Title',
                    ],
                ],
            ],
        ],
    ],
    'components/footer' => [
        [
            'section_title' => 'About Us',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[aboutus_title]',
                    'id' => 'aboutus_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'About Us',
                ],
                [
                    'name' => 'options[aboutus_description]',
                    'id' => 'aboutus_description',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'At Nea Imóveis, we are passionate about connecting people with high-quality real estate solutions. Since 2020, we’ve specialized in property sales, rentals, investments, and management.',
                ],
                [
                    'name' => 'options[aboutus_email_title]',
                    'id' => 'aboutus_email_title',
                    'type' => 'text',
                    'label' => 'Email Title',
                    'default' => 'Have a question?',
                ],
                [
                    'name' => 'options[aboutus_email_icon]',
                    'id' => 'aboutus_email_icon',
                    'type' => 'file',
                    'label' => 'Image',
                    'default' => '',
                ],
                [
                    'name' => 'options[aboutus_call_title]',
                    'id' => 'aboutus_call_title',
                    'type' => 'text',
                    'label' => 'Call Title',
                    'default' => 'Contact us at',
                ],
                [
                    'name' => 'options[aboutus_call_icon]',
                    'id' => 'aboutus_call_icon',
                    'type' => 'file',
                    'label' => 'Image',
                    'default' => '',
                ],
            ],
        ],
        [
            'section_title' => 'Contact Form Details',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_form_title]',
                    'id' => 'contact_form_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Request a Callback',
                ],
                [
                    'name' => 'options[contact_form_sub_title]',
                    'id' => 'contact_form_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Have a question? Fill in the form below, and we’ll get back to you promptly.',
                ],
                [
                    'name' => 'options[contact_form_name]',
                    'id' => 'contact_form_name',
                    'type' => 'text',
                    'label' => 'Name Label',
                    'default' => 'Name',
                ],
                [
                    'name' => 'options[contact_form_email]',
                    'id' => 'contact_form_email',
                    'type' => 'text',
                    'label' => 'Email Label',
                    'default' => 'Email',
                ],
                [
                    'name' => 'options[contact_form_phone]',
                    'id' => 'contact_form_phone',
                    'type' => 'text',
                    'label' => 'Phone Label',
                    'default' => 'Telephone',
                ],
                [
                    'name' => 'options[contact_form_btn]',
                    'id' => 'contact_form_btn',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Submit',
                ],
            ],
        ],
    ],
];
