<?php

declare(strict_types=1);

$options = [
    'home' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
                [
                    'name' => 'options[primary_title]',
                    'id' => 'primary_title',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'type_class' => 'html-header',
                    'label' => 'Title',
                    'default' => '<p>Te ayudamos</p><p>a encontrar</p><p><strong>tu nueva vivienda</strong></p>',
                ],
                [
                    'name' => 'options[primary_search_placeholder]',
                    'id' => 'primary_search_placeholder',
                    'type' => 'text',
                    'label' => 'Search Placeholder (Desktop)',
                    'default' => 'Ciudad, provincia o código postal',
                ],
                [
                    'name' => 'options[primary_search_placeholder_mobile]',
                    'id' => 'primary_search_placeholder_mobile',
                    'type' => 'text',
                    'label' => 'Search Placeholder (Mobile)',
                    'default' => 'Ciudad, provincia o CP',
                ],
                [
                    'name' => 'options[primary_search_btn_label]',
                    'id' => 'primary_search_btn_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Buscar',
                ],
            ],
        ],
        [
            'section_title' => 'Discounted Properties Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[feature_properties_title]',
                    'id' => 'feature_properties_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Las mejores rebajas en los últimos días',
                ],
                [
                    'name' => 'options[feature_properties_contact_btn]',
                    'id' => 'feature_properties_contact_btn',
                    'type' => 'text',
                    'label' => 'Contact Button Label',
                    'default' => 'Contactar',
                ],
                [
                    'name' => 'options[feature_properties_call_btn]',
                    'id' => 'feature_properties_call_btn',
                    'type' => 'text',
                    'label' => 'Call Button Label',
                    'default' => 'Llamar',
                ],
            ],
        ],
        [
            'section_title' => 'Saved Searches Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[saved_searches_title]',
                    'id' => 'saved_searches_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Últimas búsquedas guardadas',
                ],
                [
                    'name' => 'options[saved_searches_description]',
                    'id' => 'saved_searches_description',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Ver todas tus búsquedas guardadas',
                ],
            ],
        ],
        [
            'section_title' => 'Popular Locations Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[popular_location_section_title]',
                    'id' => 'popular_location_section_title',
                    'type' => 'simple-html-editor',
                    'type_class' => 'html-header',
                    'label' => 'Section Title',
                    'default' => '<p>Descubre la <strong>oferta inmobiliaria</strong></p>',
                ],
                [
                    'name' => 'popular_location_list',
                    'type' => 'array',
                    'label' => 'Location List',
                    'group_width' => 'full',
                    'limit' => 7,
                    'fields' => [
                        [
                            'name' => 'options[popular_location_list][location_img]',
                            'id' => 'location_img',
                            'type' => 'file',
                            'label' => 'Image',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[popular_location_list][location_title]',
                            'id' => 'location_title',
                            'type' => 'text',
                            'label' => 'Title',
                        ],
                        [
                            'name' => 'options[popular_location_list][location_qobrix_url]',
                            'id' => 'location_qobrix_url',
                            'type' => 'text',
                            'label' => 'Qobrix search string',
                        ],
                    ],
                    'display_fields' => [
                        'location_title' => 'Title',
                    ],
                ],
            ],
        ],
        [
            'section_title' => 'User search Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[user_search_section_title]',
                    'id' => 'user_search_section_title',
                    'type' => 'simple-html-editor',
                    'type_class' => 'html-header',
                    'label' => 'Section Title',
                    'default' => '<p>Inspiración <strong>para ti</strong></p>',
                ],
                [
                    'name' => 'user_search_list',
                    'type' => 'array',
                    'label' => 'Custom search List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[user_search_list][user_search_list_img]',
                            'id' => 'user_search_list_img',
                            'type' => 'file',
                            'label' => 'Image',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[user_search_list][user_search_list_img_label]',
                            'id' => 'user_search_list_img_label',
                            'type' => 'text',
                            'label' => 'Image Label',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[user_search_list][user_search_list_descr]',
                            'id' => 'user_search_list_descr',
                            'type' => 'text',
                            'label' => 'Description',
                        ],
                        [
                            'name' => 'options[user_search_list][user_search_list_qobrix_url]',
                            'id' => 'user_search_list_qobrix_url',
                            'type' => 'text',
                            'label' => 'Qobrix search string',
                        ],
                    ],
                    'display_fields' => [
                        'user_search_list_descr' => 'Title',
                    ],
                ],
            ],
        ],
        [
            'section_title' => 'Mortgage calculator section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[mortgage_img]',
                    'id' => 'mortgage_img',
                    'type' => 'file',
                    'label' => 'Section Image',
                ],
                [
                    'name' => 'options[mortgage_title]',
                    'id' => 'mortgage_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Calcula tu hipoteca',
                ],
                [
                    'name' => 'options[mortgage_title_img]',
                    'id' => 'mortgage_title_img',
                    'type' => 'file',
                    'label' => 'Title Image',
                ],
                [
                    'name' => 'options[mortgage_sub_title]',
                    'id' => 'mortgage_sub_title',
                    'type' => 'text',
                    'label' => 'Sub Title',
                    'default' => 'Si eres o no cliente',
                ],
                [
                    'name' => 'options[mortgage_descr]',
                    'id' => 'mortgage_descr',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => '<p>No necesitarás ningún tipo de documentación inicial.</p><p>Si eres o no cliente de CaixaBank, una cuota sin sorpresas y el plazo que mejor se adapta a ti.</p>',
                ],
                [
                    'name' => 'mortgage_services_list',
                    'type' => 'array',
                    'label' => 'Services List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[mortgage_services_list][mortgage_services_list_title]',
                            'id' => 'mortgage_services_list_title',
                            'type' => 'text',
                            'label' => 'Title',
                        ],
                    ],
                    'display_fields' => [
                        'mortgage_services_list_title' => 'Title',
                    ],
                ],
                [
                    'name' => 'options[mortgage_btn_label]',
                    'id' => 'mortgage_btn_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Calcular',
                ],
                [
                    'name' => 'options[mortgage_btn_link]',
                    'id' => 'mortgage_btn_link',
                    'type' => 'text',
                    'label' => 'Button Link',
                ],
            ],
        ],
        [
            'section_title' => 'Location Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[location_section_title]',
                    'id' => 'location_section_title',
                    'type' => 'text',
                    'label' => 'Section Title',
                    'default' => '<p>Encuentra tu vivienda por comunidad</p>',
                ],
            ],
        ],
        [
            'section_title' => 'Features Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[features_section_title]',
                    'id' => 'features_section_title',
                    'type' => 'simple-html-editor',
                    'type_class' => 'html-header',
                    'label' => 'Section Title',
                    'default' => 'La mejor solución es la que <strong>se adapta a ti.</strong>',
                ],
                [
                    'name' => 'features_list',
                    'type' => 'array',
                    'label' => 'Features List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[features_list][feature_list_img]',
                            'id' => 'feature_list_img',
                            'type' => 'file',
                            'label' => 'Image',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[features_list][feature_list_title]',
                            'id' => 'feature_list_title',
                            'type' => 'text',
                            'label' => 'Title',
                        ],
                        [
                            'name' => 'options[features_list][feature_list_descr]',
                            'id' => 'feature_list_descr',
                            'type' => 'text',
                            'label' => 'Description',
                        ],
                        [
                            'name' => 'options[features_list][feature_list_class_name]',
                            'id' => 'feature_list_class_name',
                            'type' => 'text',
                            'label' => 'Field Class',
                        ],
                        [
                            'name' => 'options[features_list][feature_list_bg_color]',
                            'id' => 'feature_list_bg_color',
                            'type' => 'color-picker',
                            'label' => 'Background Color',
                        ],
                        [
                            'name' => 'options[features_list][feature_list_url]',
                            'id' => 'feature_list_url',
                            'type' => 'text',
                            'label' => 'URL',
                        ],
                    ],
                    'display_fields' => [
                        'feature_list_title' => 'Title',
                    ],
                ],
            ],
        ],
    ],
    'properties' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
            ],
        ],
        [
            'section_title' => 'Properties Layout',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[feature_properties_contact_btn]',
                    'id' => 'feature_properties_contact_btn',
                    'type' => 'text',
                    'label' => 'Contact Button Label',
                    'default' => 'Contactar',
                ],
                [
                    'name' => 'options[feature_properties_call_btn]',
                    'id' => 'feature_properties_call_btn',
                    'type' => 'text',
                    'label' => 'Call Button Label',
                    'default' => 'Ver teléfono',
                ],
            ],
        ],
    ],
    'property' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[view_all_images_label]',
                    'id' => 'view_all_images_label',
                    'type' => 'text',
                    'label' => 'View all images Button Label',
                    'default' => 'Ver todas',
                ],
            ],
        ],
        [
            'section_title' => 'Price Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[price_section_title]',
                    'id' => 'price_section_title',
                    'type' => 'text',
                    'label' => 'Price Section Title',
                    'default' => 'Precio',
                ],
                [
                    'name' => 'options[price_label]',
                    'id' => 'price_label',
                    'type' => 'text',
                    'label' => 'Price Title',
                    'default' => 'Precio del inmueble:',
                ],
                [
                    'name' => 'options[price_label_per_sqr]',
                    'id' => 'price_label_per_sqr',
                    'type' => 'text',
                    'label' => 'Price label / m²',
                    'default' => 'Precio por m²:',
                ],
                [
                    'name' => 'options[price_btn_label]',
                    'id' => 'price_btn_label',
                    'type' => 'text',
                    'label' => 'Button Label (Not in the wishlist)',
                    'default' => 'Avisame si baja de precio',
                ],
                [
                    'name' => 'options[price_btn_wishlist_label]',
                    'id' => 'price_btn_wishlist_label',
                    'type' => 'text',
                    'label' => 'Button Label (In wishlist)',
                    'default' => 'Te avisaremos si el precio del inmueble baja.',
                ],
            ],
        ],
        [
            'section_title' => 'Mortgage calculator section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[mortgage_title]',
                    'id' => 'mortgage_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Calcula tu hipoteca con Caixabank',
                ],
                [
                    'name' => 'options[mortgage_icon]',
                    'id' => 'mortgage_icon',
                    'type' => 'file',
                    'label' => 'Icon',
                ],
                [
                    'name' => 'options[mortgage_descr]',
                    'id' => 'mortgage_descr',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => '<p>Lo hacemos fácil para tí con una hipoteca CaixaBank,</p><p>asegurando las mejores condiciones y asesoramiento financiero.</p>',
                ],
                [
                    'name' => 'options[mortgage_bg_color]',
                    'id' => 'mortgage_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Background Color',
                    'default' => '#F2F3FF',
                ],
                [
                    'name' => 'options[mortgage_btn_link]',
                    'id' => 'mortgage_btn_link',
                    'type' => 'text',
                    'label' => 'Button Link',
                ],
                [
                    'name' => 'form_title',
                    'type' => 'title',
                    'label' => 'Mobile only fields',
                ],
                [
                    'name' => 'options[mobile_mortgage_icon]',
                    'id' => 'mobile_mortgage_icon',
                    'type' => 'file',
                    'label' => 'Icon',
                ],
                [
                    'name' => 'options[mobile_mortgage_title]',
                    'id' => 'mobile_mortgage_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Simulador de hipotecas CaixaBank',
                ],
            ],
        ],
        [
            'section_title' => 'Map section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[map_title]',
                    'id' => 'map_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Ubicación',
                ],
                [
                    'name' => 'options[map_btn_label]',
                    'id' => 'map_btn_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Preguntar la dirección exacta',
                ],
                [
                    'name' => 'options[map_small_txt]',
                    'id' => 'map_small_txt',
                    'type' => 'text',
                    'label' => 'Below map description',
                    'default' => 'Dirección aproximada por deseo del anunciante.',
                ],
            ],
        ],
        [
            'section_title' => 'Information section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[information_title]',
                    'id' => 'information_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Equipa tu vivienda con Facilitea',
                ],
                [
                    'name' => 'options[information_icon]',
                    'id' => 'information_icon',
                    'type' => 'file',
                    'label' => 'Icon',
                ],
                [
                    'name' => 'options[information_descr]',
                    'id' => 'information_descr',
                    'group_width' => 'full',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'default' => '<p>¿Ya elegiste tu hogar ideal? Equipa tu hogar con todo lo que necesitas para convertirlo en un espacio acogedor y funcional.</p>',
                ],
                [
                    'name' => 'options[information_bg_color]',
                    'id' => 'information_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Background Color',
                    'default' => '#F1F1ED',
                ],
                [
                    'name' => 'options[information_btn_link]',
                    'id' => 'information_btn_link',
                    'type' => 'text',
                    'label' => 'Button Link',
                ],
            ],
        ],
        [
            'section_title' => 'Similar properties section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[similar_properties_title]',
                    'id' => 'similar_properties_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Title',
                    'default' => 'También te puede gustar',
                ],
                [
                    'name' => 'options[feature_properties_contact_btn]',
                    'id' => 'feature_properties_contact_btn',
                    'type' => 'text',
                    'label' => 'Contact Button Label',
                    'default' => 'Contactar',
                ],
                [
                    'name' => 'options[feature_properties_call_btn]',
                    'id' => 'feature_properties_call_btn',
                    'type' => 'text',
                    'label' => 'Call Button Label',
                    'default' => 'Llamar',
                ],
            ],
        ],
    ],
    'components/contact-us-form' => [
        [
            'section_title' => 'Contact us form component',
            'section_description' => 'This form is visible on homepage/listing and single property page',
            'fields' => [
                [
                    'name' => 'options[contact_us_header_label]',
                    'id' => 'contact_us_header_label',
                    'type' => 'text',
                    'label' => 'Header Label',
                    'default' => 'Ofrecido por',
                ],
                [
                    'name' => 'options[contact_us_header_icon]',
                    'id' => 'contact_us_header_icon',
                    'type' => 'file',
                    'label' => 'Header Icon',
                ],
                [
                    'name' => 'options[contact_us_header_btn_label]',
                    'id' => 'contact_us_header_btn_label',
                    'type' => 'text',
                    'label' => 'Header Button Label',
                    'default' => 'Ver teléfono',
                ],
                [
                    'name' => 'form_title',
                    'type' => 'title',
                    'label' => 'Form',
                ],
                [
                    'name' => 'options[contact_us_title]',
                    'id' => 'contact_us_title',
                    'type' => 'text',
                    'label' => 'Form Title',
                    'default' => 'Contacta con el anunciante',
                ],
                [
                    'name' => 'options[contact_us_sub_title]',
                    'id' => 'contact_us_sub_title',
                    'type' => 'text',
                    'label' => 'Form Sub Title',
                    'default' => 'Completa el formulario para contactar con el anunciante y ver su número de teléfono.',
                ],
                [
                    'name' => 'options[contact_us_counteroffer_title]',
                    'id' => 'contact_us_counteroffer_title',
                    'type' => 'text',
                    'label' => 'CounterOffer Form Title',
                    'default' => 'Hacer una contraoferta',
                ],
                [
                    'name' => 'options[contact_us_name_label]',
                    'id' => 'contact_us_name_label',
                    'type' => 'text',
                    'label' => 'Form Name Placeholder',
                    'default' => 'Nombre',
                ],
                [
                    'name' => 'options[contact_us_email_label]',
                    'id' => 'contact_us_email_label',
                    'type' => 'text',
                    'label' => 'Form Email Placeholder',
                    'default' => 'Correo electrónico',
                ],
                [
                    'name' => 'options[contact_us_phone_label]',
                    'id' => 'contact_us_phone_label',
                    'type' => 'text',
                    'label' => 'Form Phone Placeholder',
                    'default' => 'Número móvil',
                ],
                [
                    'name' => 'options[contact_us_counteroffer_label]',
                    'id' => 'contact_us_counteroffer_label',
                    'type' => 'text',
                    'label' => 'Form Counteroffer Placeholder',
                    'default' => 'Precio propuesto',
                ],
                [
                    'name' => 'options[contact_us_message_title]',
                    'id' => 'contact_us_message_title',
                    'type' => 'text',
                    'label' => 'Form Comment Title',
                    'default' => 'Añadir comentario (opcional)',
                ],
                [
                    'name' => 'options[contact_us_message_label]',
                    'id' => 'contact_us_message_label',
                    'type' => 'text',
                    'label' => 'Form Comment Placeholder',
                    'default' => 'Comentario',
                ],
                [
                    'name' => 'options[contact_us_description]',
                    'id' => 'contact_us_description',
                    'type' => 'simple-html-editor',
                    'label' => 'Form Description',
                    'default' => '<p>Facilitea comunicará los datos facilitados al anunciante del inmueble para atender su solicitud. El anunciante los tratará en calidad de responsable y le informará de su tratamiento.</p>',
                ],
                [
                    'name' => 'options[contact_us_description_alt]',
                    'id' => 'contact_us_description_alt',
                    'type' => 'simple-html-editor',
                    'label' => 'Form Description Alternative',
                    'description' => 'This will be used when the contact reason field value is `Solicitar información del inmueble y financiación`',
                    'default' => '<p>Facilitea comunicará los datos facilitados al anunciante para atender tu solicitud de informacion del inmueble y a CaixaBank para atender tu solicitud de información sobre la financiación. Ambos trataran los datos en calidad de responsables y te informaran del tratamiento de tus datos.</p>',
                ],
                [
                    'name' => 'options[contact_us_caixa_customer_label]',
                    'id' => 'contact_us_caixa_customer_label',
                    'type' => 'text',
                    'label' => 'Caixa Customer Checkbox Label',
                    'description' => 'This will be used when the contact reason field value is `Solicitar información del inmueble y financiación`',
                    'default' => 'Soy cliente CaixaBank',
                ],
                [
                    'name' => 'options[contact_us_caixa_customer_description]',
                    'id' => 'contact_us_caixa_customer_description',
                    'type' => 'simple-html-editor',
                    'label' => 'Caixa Customer Checkbox Description',
                    'description' => 'This will be used when the contact reason field value is `Solicitar información del inmueble y financiación`',
                    'default' => '<p>Para darte información más precisa sobre la financiación, necesitamos saber si eres cliente de CaixaBank.</p>',
                ],
                [
                    'name' => 'options[contact_us_btn_label]',
                    'id' => 'contact_us_btn_label',
                    'type' => 'text',
                    'label' => 'Form Button Label',
                    'default' => 'Contactar',
                ],
                [
                    'name' => 'options[contact_us_btn_label_mobile]',
                    'id' => 'contact_us_btn_label_mobile',
                    'type' => 'text',
                    'label' => 'Form Button Label - Mobile',
                    'default' => 'Enviar',
                ],
            ],
        ],
    ],
    'components/imagin' => [
        [
            'section_title' => 'Imagin component',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[imagin_title]',
                    'id' => 'imagin_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Simulador de hipotecas imaginBank',
                ],
                [
                    'name' => 'options[imagin_description]',
                    'id' => 'imagin_description',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Puedes simular la cuota con la calculadora de hipotecas imaginBank .',
                ],
                [
                    'name' => 'options[imagin_img]',
                    'id' => 'imagin_img',
                    'type' => 'file',
                    'label' => 'Icon',
                ],
                [
                    'name' => 'imagin_modal_title',
                    'type' => 'title',
                    'label' => 'Modal Imagin Content',
                ],
                [
                    'name' => 'options[modal_imagin_title]',
                    'id' => 'modal_imagin_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Estás siendo redirigido al simulador',
                ],
                [
                    'name' => 'options[modal_imagin_description]',
                    'id' => 'modal_imagin_description',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'de hipotecas imaginBank…',
                ],
            ],
        ],
    ],
    'about' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
                [
                    'name' => 'options[about_title]',
                    'id' => 'about_title',
                    'type' => 'normal-html-editor',
                    'label' => 'Title',
                    'default' => '<p>Sobre</p><p>Facilitea Casas</p>',
                ],
            ],
        ],
        [
            'section_title' => '2nd Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[about_description]',
                    'id' => 'about_description',
                    'type' => 'normal-html-editor',
                    'label' => 'Description',
                    'group_width' => 'full',
                    'default' => '<p>Facilitamos tus decisiones vitales para que puedas avanzar y conseguir todo aquello que es importante para ti y que te ayuda a construir los espacios de vida que quieres tener.</p>',
                ],
            ],
        ],
        [
            'section_title' => '3rd Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[third_section_bg_img]',
                    'id' => 'third_section_bg_img',
                    'type' => 'file',
                    'label' => 'Image',
                    'default' => '',
                ],
                [
                    'name' => 'options[third_section_bg_color]',
                    'id' => 'third_section_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Background Color',
                    'default' => '#BDC3FF',
                ],
                [
                    'name' => 'options[third_section_description]',
                    'id' => 'third_section_description',
                    'type' => 'normal-html-editor',
                    'label' => 'Description',
                    'default' => '<p>La mejor solución es aquella que mejor se adapta a ti, por eso estamos siempre a tu lado para entender la mejor forma de ayudarte a prosperar y conseguir lo que quieres.</p>',
                ],
                [
                    'name' => 'options[third_section_btn_lbl]',
                    'id' => 'third_section_btn_lbl',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Siempre a tu lado',
                ],
            ],
        ],
        [
            'section_title' => '5th Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[fifth_section_bg_img]',
                    'id' => 'fifth_section_bg_img',
                    'type' => 'file',
                    'label' => 'Image',
                    'default' => '',
                ],
                [
                    'name' => 'options[fifth_section_title]',
                    'id' => 'fifth_section_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => '<p>La mejor solución es aquella que mejor se adapta a ti.</p>',
                ],
                [
                    'name' => 'solution_list',
                    'type' => 'array',
                    'label' => 'Solution List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[solution_list][solution_list_title]',
                            'id' => 'solution_list_title',
                            'type' => 'simple-html-editor',
                            'label' => 'Title',
                        ],
                        [
                            'name' => 'options[solution_list][solution_list_link]',
                            'id' => 'solution_list_link',
                            'type' => 'text',
                            'label' => 'Link',
                        ],
                    ],
                    'display_fields' => [
                        'solution_list_title' => 'Title',
                    ],
                ],
            ],
        ],
        [
            'section_title' => 'Contact Us Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[sixth_section_bg_img]',
                    'id' => 'sixth_section_bg_img',
                    'type' => 'file',
                    'label' => 'Image',
                    'default' => '',
                ],
                [
                    'name' => 'options[sixth_section_title]',
                    'id' => 'sixth_section_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => '¿Tienes alguna duda? Contacta con nosotros',
                ],
                [
                    'name' => 'options[sixth_section_description]',
                    'id' => 'sixth_section_description',
                    'type' => 'normal-html-editor',
                    'label' => 'Description',
                    'default' => '<p>Nuestro equipo está aquí para ayudarte, ponte en contacto con nosotros y te daremos respuesta lo antes posible.</p>',
                ],
                [
                    'name' => 'options[sixth_section_btn_lbl]',
                    'id' => 'sixth_section_btn_lbl',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Contactar',
                ],
            ],
        ],
        [
            'section_title' => 'Location Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[location_section_title]',
                    'id' => 'location_section_title',
                    'type' => 'text',
                    'label' => 'Section Title',
                    'default' => 'Encuentra tu vivienda por comunidad',
                ],
            ],
        ],
        [
            'section_title' => 'Features Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[features_section_title]',
                    'id' => 'features_section_title',
                    'type' => 'simple-html-editor',
                    'type_class' => 'html-header',
                    'label' => 'Section Title',
                    'default' => 'La mejor solución es la que <strong>se adapta a ti.</strong>',
                ],
                [
                    'name' => 'features_list',
                    'type' => 'array',
                    'label' => 'Features List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[features_list][feature_list_img]',
                            'id' => 'feature_list_img',
                            'type' => 'file',
                            'label' => 'Image',
                            'default' => '',
                        ],
                        [
                            'name' => 'options[features_list][feature_list_title]',
                            'id' => 'feature_list_title',
                            'type' => 'text',
                            'label' => 'Title',
                        ],
                        [
                            'name' => 'options[features_list][feature_list_descr]',
                            'id' => 'feature_list_descr',
                            'type' => 'text',
                            'label' => 'Description',
                        ],
                        [
                            'name' => 'options[features_list][feature_list_class_name]',
                            'id' => 'feature_list_class_name',
                            'type' => 'text',
                            'label' => 'Field Class',
                        ],
                        [
                            'name' => 'options[features_list][feature_list_bg_color]',
                            'id' => 'feature_list_bg_color',
                            'type' => 'color-picker',
                            'label' => 'Background Color',
                        ],
                        [
                            'name' => 'options[features_list][feature_list_url]',
                            'id' => 'feature_list_url',
                            'type' => 'text',
                            'label' => 'URL',
                        ],
                    ],
                    'display_fields' => [
                        'feature_list_title' => 'Title',
                    ],
                ],
            ],
        ],
    ],
    'contact' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[primary_section_icon]',
                    'id' => 'primary_section_icon',
                    'type' => 'file',
                    'label' => 'Icon',
                ],
                [
                    'name' => 'options[primary_section_title]',
                    'id' => 'primary_section_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Contacta con nosotros',
                ],
                [
                    'name' => 'options[primary_section_sub_title]',
                    'id' => 'primary_section_sub_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => '¿Tienes alguna duda? Ponte en contacto con nosotros y te daremos respuesta lo antes posible.',
                ],
            ],
        ],
        [
            'section_title' => 'Contact us form section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_us_title]',
                    'id' => 'contact_us_title',
                    'type' => 'text',
                    'group_width' => 'full',
                    'label' => 'Title',
                    'default' => 'Formulario de contacto',
                ],
                [
                    'name' => 'options[contact_us_name_label]',
                    'id' => 'contact_us_name_label',
                    'type' => 'text',
                    'label' => 'Name Placeholder',
                    'default' => 'Nombre',
                ],
                [
                    'name' => 'options[contact_us_email_label]',
                    'id' => 'contact_us_email_label',
                    'type' => 'text',
                    'label' => 'Email Placeholder',
                    'default' => 'Correo electrónico',
                ],
                [
                    'name' => 'options[contact_us_phone_label]',
                    'id' => 'contact_us_phone_label',
                    'type' => 'text',
                    'label' => 'Phone Placeholder',
                    'default' => 'Número móvil',
                ],
                [
                    'name' => 'options[contact_us_message_label]',
                    'id' => 'contact_us_message_label',
                    'type' => 'text',
                    'label' => 'Comment Placeholder',
                    'default' => 'Comentario',
                ],
                [
                    'name' => 'options[contact_us_description]',
                    'id' => 'contact_us_description',
                    'type' => 'simple-html-editor',
                    'label' => 'Description',
                    'group_width' => 'full',
                    'default' => '<p>El responsable de los datos es Facilitea SelectPlace S.L.U. Los datos facilitados serán tratados para atender su solicitud de contacto. Puede ejercer sus derechos y acceder a la informacion completa de como trataremos sus datos en www.facilitea.com/politicaprivacidad.</p>',
                ],
                [
                    'name' => 'options[contact_us_btn_label]',
                    'id' => 'contact_us_btn_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Contactar',
                ],
                [
                    'name' => 'options[contact_us_second_column_title]',
                    'id' => 'contact_us_second_column_title',
                    'type' => 'text',
                    'label' => 'Second Column Title',
                    'default' => 'También puedes encontrarnos en:',
                ],
                [
                    'name' => 'options[owner_id]',
                    'id' => 'owner_id',
                    'type' => 'text',
                    'group_width' => 'full',
                    'description' => 'This will be used as the default user for receiving the email notifications from qobrix',
                    'label' => 'Qobrix user id',
                ],
            ],
        ],
    ],
    'legal_notice' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[primary_section_content]',
                    'id' => 'primary_section_content',
                    'type' => 'advance-html-editor',
                    'label' => 'Content',
                    'group_width' => 'full',
                    'default' => '',
                ],
            ],
        ],
    ],
    'custom_html' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[primary_section_content]',
                    'id' => 'primary_section_content',
                    'type' => 'advance-html-editor',
                    'label' => 'Content',
                    'group_width' => 'full',
                    'default' => '',
                ],
            ],
        ],
    ],
    'terms_and_conditions' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[primary_section_content]',
                    'id' => 'primary_section_content',
                    'type' => 'advance-html-editor',
                    'label' => 'Content',
                    'group_width' => 'full',
                    'default' => '',
                ],
            ],
        ],
    ],
    'privacy_policy' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[primary_section_content]',
                    'id' => 'primary_section_content',
                    'type' => 'advance-html-editor',
                    'label' => 'Content',
                    'group_width' => 'full',
                    'default' => '',
                ],
            ],
        ],
    ],
    'cookie_policy' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[primary_section_content]',
                    'id' => 'primary_section_content',
                    'type' => 'advance-html-editor',
                    'label' => 'Before Cookie Content',
                    'group_width' => 'full',
                    'default' => '',
                ],
                [
                    'name' => 'options[primary_section_content_after]',
                    'id' => 'primary_section_content_after',
                    'type' => 'advance-html-editor',
                    'label' => 'After Cookie Content',
                    'group_width' => 'full',
                    'default' => '',
                ],
                [
                    'name' => 'options[cookies_saved_btn_label]',
                    'id' => 'cookies_saved_btn_label',
                    'type' => 'text',
                    'label' => 'Cookie Save Button Label',
                    'default' => 'Guardar y continuar',
                ],
            ],
        ],
    ],
    'how_it_works' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[hero_image]',
                    'id' => 'hero_image',
                    'type' => 'file',
                    'label' => 'Background Image',
                ],
                [
                    'name' => 'options[about_title]',
                    'id' => 'about_title',
                    'type' => 'normal-html-editor',
                    'label' => 'Title',
                    'default' => '<p>Cómo</p><p><b>funciona</b></p>',
                ],
            ],
        ],
        [
            'section_title' => '2nd Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[second_section_title]',
                    'id' => 'second_section_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Lo que buscas en un clic',
                ],
                [
                    'name' => 'options[second_section_badge]',
                    'id' => 'second_section_badge',
                    'type' => 'text',
                    'label' => 'Title Badge',
                    'default' => 'Fácil',
                ],
                [
                    'name' => 'options[second_section_description]',
                    'id' => 'second_section_description',
                    'type' => 'normal-html-editor',
                    'label' => 'Description',
                    'group_width' => 'full',
                    'default' => '<p>para que puedas avanzar y conseguir todo aquello que es importante para tí.</p>',
                ],
            ],
        ],
        [
            'section_title' => 'Services Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'services_list',
                    'type' => 'array',
                    'label' => 'Features List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[services_list][services_list_img]',
                            'id' => 'services_list_img',
                            'type' => 'file',
                            'label' => 'Icon',
                        ],
                        [
                            'name' => 'options[services_list][services_list_title]',
                            'id' => 'services_list_title',
                            'type' => 'text',
                            'label' => 'Title',
                        ],
                        [
                            'name' => 'options[services_list][services_list_descr]',
                            'id' => 'services_list_descr',
                            'type' => 'text',
                            'label' => 'Description',
                        ],
                        [
                            'name' => 'options[services_list][services_list_bg_color]',
                            'id' => 'services_list_bg_color',
                            'type' => 'color-picker',
                            'label' => 'Background Color',
                            'default' => '#F1F1ED',
                        ],
                        [
                            'name' => 'options[services_list][services_list_btn_lbl]',
                            'id' => 'services_list_btn_lbl',
                            'type' => 'text',
                            'label' => 'Button Label',
                        ],
                        [
                            'name' => 'options[services_list][services_list_btn_class_name]',
                            'id' => 'services_list_btn_class_name',
                            'type' => 'text',
                            'label' => 'Button Class',
                        ],
                        [
                            'name' => 'options[services_list][services_list_btn_link]',
                            'id' => 'services_list_btn_link',
                            'type' => 'text',
                            'label' => 'Button Link',
                        ],
                    ],
                    'display_fields' => [
                        'services_list_title' => 'Title',
                    ],
                ],
            ],
        ],
        [
            'section_title' => '4th Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[forth_section_bg_img]',
                    'id' => 'forth_section_bg_img',
                    'type' => 'file',
                    'label' => 'Image',
                    'default' => '',
                ],
                [
                    'name' => 'options[forth_section_title]',
                    'id' => 'forth_section_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => '<p>La mejor solución es aquella que mejor se adapta a ti.</p>',
                ],
                [
                    'name' => 'solution_list',
                    'type' => 'array',
                    'label' => 'Solution List',
                    'group_width' => 'full',
                    'fields' => [
                        [
                            'name' => 'options[solution_list][solution_list_title]',
                            'id' => 'solution_list_title',
                            'type' => 'simple-html-editor',
                            'label' => 'Title',
                        ],
                        [
                            'name' => 'options[solution_list][solution_list_link]',
                            'id' => 'solution_list_link',
                            'type' => 'text',
                            'label' => 'Link',
                        ],
                    ],
                    'display_fields' => [
                        'solution_list_title' => 'Title',
                    ],
                ],
            ],
        ],
        [
            'section_title' => 'Contact Us Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_us_bg_img]',
                    'id' => 'contact_us_bg_img',
                    'type' => 'file',
                    'label' => 'Image',
                    'default' => '',
                ],
                [
                    'name' => 'options[contact_us_title]',
                    'id' => 'contact_us_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => '¿Tienes alguna duda? Contacta con nosotros',
                ],
                [
                    'name' => 'options[contact_us_description]',
                    'id' => 'contact_us_description',
                    'type' => 'normal-html-editor',
                    'label' => 'Description',
                    'default' => '<p>Nuestro equipo está aquí para ayudarte, ponte en contacto con nosotros y te daremos respuesta lo antes posible.</p>',
                ],
                [
                    'name' => 'options[contact_us_btn_lbl]',
                    'id' => 'contact_us_btn_lbl',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Contactar',
                ],
            ],
        ],
        [
            'section_title' => 'Location Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[location_section_title]',
                    'id' => 'location_section_title',
                    'type' => 'text',
                    'label' => 'Section Title',
                    'default' => 'Encuentra tu vivienda por comunidad',
                ],
            ],
        ],
    ],
    'wishlist' => [
    ],
    'saved_searches' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[sub_title]',
                    'id' => 'sub_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Todas tus búsquedas guardadas',
                ],
            ],
        ],
    ],
    'components/modals' => [
        [
            'section_title' => 'Favoritos',
            'section_description' => 'Modal content for favoritos in all pages',
            'fields' => [
                [
                    'name' => 'wishlist_login',
                    'type' => 'title',
                    'label' => 'No Login Content',
                ],
                [
                    'name' => 'options[wishlist_login_title_1]',
                    'id' => 'wishlist_login_title_1',
                    'type' => 'text',
                    'label' => 'Title Section 1',
                    'default' => 'Favoritos',
                ],
                [
                    'name' => 'options[wishlist_login_sub_title_1]',
                    'id' => 'wishlist_login_sub_title_1',
                    'type' => 'text',
                    'label' => 'Sub-Title Section 1',
                    'default' => 'Ten a mano los que más te gustan',
                ],
                [
                    'name' => 'options[wishlist_login_descr_1]',
                    'id' => 'wishlist_login_descr_1',
                    'type' => 'simple-html-editor',
                    'label' => 'Description Section 1',
                    'group_width' => 'full',
                    'default' => '<p>Tus favoritos se guardarán en tu perfil y recibirás notificaciones cuando haya novedades.</p>',
                ],
                [
                    'name' => 'options[wishlist_login_title_2]',
                    'id' => 'wishlist_login_title_2',
                    'type' => 'simple-html-editor',
                    'label' => 'Title Section 2',
                    'group_width' => 'full',
                    'default' => '<p>Inicia sesión o crea una cuenta</p><p>para avisos de favoritos.</p>',
                ],
                [
                    'name' => 'options[wishlist_login_btn_2]',
                    'id' => 'wishlist_login_btn_2',
                    'type' => 'text',
                    'label' => 'Button Label Section 2',
                    'default' => 'Acceder',
                ],
                [
                    'name' => 'options[wishlist_login_descr_2]',
                    'id' => 'wishlist_login_descr_2',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Accede a nuestros servicios Facilitea utilizando el mismo correo electrónico y contraseña.',
                ],
                [
                    'name' => 'wishlist_success',
                    'type' => 'title',
                    'label' => 'Successful Content',
                ],
                [
                    'name' => 'options[wishlist_success_message]',
                    'id' => 'wishlist_success_message',
                    'type' => 'text',
                    'label' => 'Icon Message when added',
                    'default' => 'Inmueble guardado en tu lista de favoritos',
                ],
                [
                    'name' => 'options[wishlist_success_message_removed]',
                    'id' => 'wishlist_success_message_removed',
                    'type' => 'text',
                    'label' => 'Icon Message when remove',
                    'default' => 'Inmueble eliminada de tu lista de favoritos',
                ],
                [
                    'name' => 'options[wishlist_success_title]',
                    'id' => 'wishlist_success_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => '¿Quieres ver todos tus favoritos?',
                ],
                [
                    'name' => 'options[wishlist_success_descr]',
                    'id' => 'wishlist_success_descr',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Accede a la lista completa de tus inmuebles favoritos en un solo lugar.',
                ],
                [
                    'name' => 'options[wishlist_success_btn_lbl]',
                    'id' => 'wishlist_success_btn_lbl',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Ver mis favoritos',
                ],
                [
                    'name' => 'wishlist_failed',
                    'type' => 'title',
                    'label' => 'Failed Content',
                ],
                [
                    'name' => 'options[wishlist_failed_message]',
                    'id' => 'wishlist_failed_message',
                    'type' => 'text',
                    'label' => 'Icon Message when adding',
                    'default' => 'No se ha podido guardar la vivienda en tu lista de favoritos. Por favor vuelve a intentarlo.',
                ],
                [
                    'name' => 'options[wishlist_failed_message_remove]',
                    'id' => 'wishlist_failed_message_remove',
                    'type' => 'text',
                    'label' => 'Icon Message when removing',
                    'default' => 'No se ha podido eliminar la vivienda de tu lista de favoritos. Por favor vuelve a intentarlo.',
                ],
                [
                    'name' => 'options[wishlist_failed_btn_lbl]',
                    'id' => 'wishlist_failed_btn_lbl',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Volver a intentar',
                ],
            ],
        ],
        [
            'section_title' => 'Saved Searches',
            'section_description' => 'Modal content for saved searches in all pages',
            'fields' => [
                [
                    'name' => 'options[saved_search_lbl]',
                    'id' => 'saved_search_lbl',
                    'type' => 'text',
                    'label' => 'Saved Search Label',
                    'default' => 'Guardar criterios de búsqueda',
                ],
                [
                    'name' => 'options[saved_search_after_save_lbl]',
                    'id' => 'saved_search_after_save_lbl',
                    'type' => 'text',
                    'label' => 'Saved Search After Save Label',
                    'default' => 'Búsquedas guardada',
                ],
                [
                    'name' => 'options[saved_search_see_all_lbl]',
                    'id' => 'saved_search_see_all_lbl',
                    'type' => 'text',
                    'label' => 'Saved Search See All Label',
                    'default' => 'Ver todas mis búsquedas',
                ],
                [
                    'name' => 'saved_searches_title_new',
                    'type' => 'title',
                    'label' => 'New Saved Search Content',
                ],
                [
                    'name' => 'options[saved_search_new_title]',
                    'id' => 'saved_search_new_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Guardar búsqueda',
                ],
                [
                    'name' => 'options[saved_search_new_descr]',
                    'id' => 'saved_search_new_descr',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Recibirás notificaciones a tu correo de nuevos inmuebles según tus criterios de búsqueda.',
                ],
                [
                    'name' => 'options[saved_search_new_field_lbl]',
                    'id' => 'saved_search_new_field_lbl',
                    'type' => 'text',
                    'label' => 'Input Label',
                    'default' => 'Guardar búsqueda',
                ],
                [
                    'name' => 'options[saved_search_new_field_placeholder]',
                    'id' => 'saved_search_new_field_placeholder',
                    'type' => 'text',
                    'label' => 'Input Placeholder',
                    'default' => 'Inmuebles en',
                ],
                [
                    'name' => 'options[saved_search_new_criteria_title]',
                    'id' => 'saved_search_new_criteria_title',
                    'type' => 'text',
                    'label' => 'Criteria Title',
                    'default' => 'Criterios de búsqueda',
                ],
                [
                    'name' => 'options[saved_search_new_btn_lbl]',
                    'id' => 'saved_search_new_btn_lbl',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Guardar búsqueda',
                ],
                [
                    'name' => 'saved_searches_title_success',
                    'type' => 'title',
                    'label' => 'Success Content',
                ],
                [
                    'name' => 'options[saved_search_success_title]',
                    'id' => 'saved_search_success_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Búsqueda guardada',
                ],
                [
                    'name' => 'options[saved_search_success_descr]',
                    'id' => 'saved_search_success_descr',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Recibirás notificaciones a tu correo de nuevos inmuebles según tu búsqueda guardada.',
                ],
                [
                    'name' => 'options[saved_search_success_btn_lbl]',
                    'id' => 'saved_search_success_btn_lbl',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Ver búsquedas guardadas',
                ],
                [
                    'name' => 'saved_searches_title_failed',
                    'type' => 'title',
                    'label' => 'Failed Content',
                ],
                [
                    'name' => 'options[saved_search_failed_descr]',
                    'id' => 'saved_search_failed_descr',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'No se ha podido guardar la búsqueda. Por favor vuelva a intentarlo.',
                ],
                [
                    'name' => 'options[saved_search_failed_btn_lbl]',
                    'id' => 'saved_search_failed_btn_lbl',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Volver a intentar',
                ],
                [
                    'name' => 'saved_searches_title_login',
                    'type' => 'title',
                    'label' => 'Login Content',
                ],
                [
                    'name' => 'options[saved_search_login_title_1]',
                    'id' => 'saved_search_login_title_1',
                    'type' => 'text',
                    'label' => 'Title Section 1',
                    'default' => 'Búsquedas guardadas',
                ],
                [
                    'name' => 'options[saved_search_login_sub_title_1]',
                    'id' => 'saved_search_login_sub_title_1',
                    'type' => 'text',
                    'label' => 'Sub-Title Section 1',
                    'default' => 'Personaliza tus búsquedas y recibe novedades',
                ],
                [
                    'name' => 'options[saved_search_login_descr_1]',
                    'id' => 'saved_search_login_descr_1',
                    'type' => 'simple-html-editor',
                    'label' => 'Description Section 1',
                    'group_width' => 'full',
                    'default' => '<p>Las búsquedas se guardarán en tu perfil y recibirás notificaciones cuando haya novedades que coincidan con lo que buscas.</p>',
                ],
                [
                    'name' => 'options[saved_search_login_title_2]',
                    'id' => 'saved_search_login_title_2',
                    'type' => 'simple-html-editor',
                    'label' => 'Title Section 2',
                    'group_width' => 'full',
                    'default' => '<p>Inicia sesión o crea una cuenta</p><p>para avisos de búsquedas guardadas.</p>',
                ],
                [
                    'name' => 'options[saved_search_login_btn_2]',
                    'id' => 'saved_search_login_btn_2',
                    'type' => 'text',
                    'label' => 'Button Label Section 2',
                    'default' => 'Acceder',
                ],
                [
                    'name' => 'options[saved_search_login_descr_2]',
                    'id' => 'saved_search_login_descr_2',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Accede a nuestros servicios Facilitea utilizando el mismo correo electrónico y contraseña.',
                ],
            ],
        ],
        [
            'section_title' => 'Price Drop',
            'section_description' => 'Modal content for price drop in property page',
            'fields' => [
                [
                    'name' => 'price_drop_login',
                    'type' => 'title',
                    'label' => 'No Login Content',
                ],
                [
                    'name' => 'options[price_drop_login_title_1]',
                    'id' => 'price_drop_login_title_1',
                    'type' => 'text',
                    'label' => 'Title Section 1',
                    'default' => 'Avísame si baja',
                ],
                [
                    'name' => 'options[price_drop_login_sub_title_1]',
                    'id' => 'price_drop_login_sub_title_1',
                    'type' => 'text',
                    'label' => 'Sub-Title Section 1',
                    'default' => 'Suscríbete a la bajada de precio y no pierdas ninguna oportunidad.',
                ],
                [
                    'name' => 'options[price_drop_login_descr_1]',
                    'id' => 'price_drop_login_descr_1',
                    'type' => 'simple-html-editor',
                    'label' => 'Description Section 1',
                    'group_width' => 'full',
                    'default' => '<p>El inmueble se guardará en los favoritos de tu perfil y recibirás notificaciones sobre cualquier cambio.</p>',
                ],
                [
                    'name' => 'options[price_drop_login_title_2]',
                    'id' => 'price_drop_login_title_2',
                    'type' => 'simple-html-editor',
                    'label' => 'Title Section 2',
                    'group_width' => 'full',
                    'default' => '<p>Inicia sesión o crea una cuenta</p><p>para avisos de bajada de precio.</p>',
                ],
                [
                    'name' => 'options[price_drop_login_btn_2]',
                    'id' => 'price_drop_login_btn_2',
                    'type' => 'text',
                    'label' => 'Button Label Section 2',
                    'default' => 'Acceder',
                ],
                [
                    'name' => 'options[price_drop_login_descr_2]',
                    'id' => 'price_drop_login_descr_2',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Accede a nuestros servicios Facilitea utilizando el mismo correo electrónico y contraseña.',
                ],
                [
                    'name' => 'price_drop',
                    'type' => 'title',
                    'label' => 'Successful Content',
                ],
                [
                    'name' => 'options[price_drop_message]',
                    'id' => 'price_drop_message',
                    'type' => 'text',
                    'label' => 'Icon Message when added',
                    'default' => 'Inmueble guardado en tu lista de favoritos',
                ],
                [
                    'name' => 'options[price_drop_title]',
                    'id' => 'price_drop_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Aviso de bajada de precio',
                ],
                [
                    'name' => 'options[price_drop_descr]',
                    'id' => 'price_drop_descr',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'El inmueble se agregará automáticamente a tu lista de favoritos y te notificaremos si el precio cambia, se añaden nuevas fotos o si el inmueble es eliminado.',
                ],
            ],
        ],
        [
            'section_title' => 'Agent telephone',
            'section_description' => 'Modal content for agent phone',
            'fields' => [
                [
                    'name' => 'options[agent_phone_login_title_1]',
                    'id' => 'agent_phone_login_title_1',
                    'type' => 'text',
                    'label' => 'Title Section 1',
                    'default' => 'Contacta con el anunciante',
                ],
                [
                    'name' => 'options[agent_phone_login_sub_title_1]',
                    'id' => 'agent_phone_login_sub_title_1',
                    'type' => 'text',
                    'label' => 'Sub-Title Section 1',
                    'default' => 'Accede para ver el teléfono de contacto',
                ],
                [
                    'name' => 'options[agent_phone_login_descr_1]',
                    'id' => 'agent_phone_login_descr_1',
                    'type' => 'simple-html-editor',
                    'label' => 'Description Section 1',
                    'group_width' => 'full',
                    'default' => '<p>Inicia sesión o regístrate para visualizar los datos de contacto y poder comunicarte directamente con el anunciante.</p>',
                ],
                [
                    'name' => 'options[agent_phone_login_title_2]',
                    'id' => 'agent_phone_login_title_2',
                    'type' => 'simple-html-editor',
                    'label' => 'Title Section 2',
                    'group_width' => 'full',
                    'default' => '<p>Inicia sesión o crea una cuenta</p><p>para ver el teléfono de contacto.</p>',
                ],
                [
                    'name' => 'options[agent_phone_login_btn_2]',
                    'id' => 'agent_phone_login_btn_2',
                    'type' => 'text',
                    'label' => 'Button Label Section 2',
                    'default' => 'Acceder',
                ],
                [
                    'name' => 'options[agent_phone_login_descr_2]',
                    'id' => 'agent_phone_login_descr_2',
                    'type' => 'text',
                    'label' => 'Description',
                    'default' => 'Accede a nuestros servicios Facilitea utilizando el mismo correo electrónico y contraseña.',
                ],
            ],
        ],
    ],
    'notifications' => [
        [
            'section_title' => 'Primary Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[primary_section_title]',
                    'id' => 'primary_section_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Notificaciones',
                ],
                [
                    'name' => 'options[primary_section_desc]',
                    'id' => 'primary_section_desc',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => 'Description',
                    'default' => 'Configura tus notificaciones para recibir solo las actualizaciones que más te interesan.',
                ],
                [
                    'name' => 'favoritos_title',
                    'type' => 'title',
                    'label' => 'Favoritos',
                ],
                [
                    'name' => 'options[primary_section_fav_title]',
                    'id' => 'primary_section_fav_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Favoritos',
                ],
                [
                    'name' => 'options[primary_section_fav_desc]',
                    'id' => 'primary_section_fav_desc',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => 'Description',
                    'default' => 'Recibe notificaciones cada vez que haya actualizaciones o cambios en tus inmuebles favoritos, para que siempre estés al tanto.',
                ],
                [
                    'name' => 'saved_searches_title',
                    'type' => 'title',
                    'label' => 'Saved Searches',
                ],
                [
                    'name' => 'options[primary_section_saved_search_title]',
                    'id' => 'primary_section_saved_search_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => 'Búsquedas guardadas',
                ],
                [
                    'name' => 'options[primary_section_saved_search_desc]',
                    'id' => 'primary_section_saved_search_desc',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => 'Description',
                    'default' => 'Actualmente, tienes %1d búsquedas activas. Para gestionarlas, accede a la sección de búsquedas guardadas.',
                ],
            ],
        ],
        [
            'section_title' => 'Contact us Section',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[contact_us_title]',
                    'id' => 'contact_us_title',
                    'type' => 'text',
                    'label' => 'Title',
                    'default' => '¿Tienes alguna duda? Contacta con nosotros',
                ],
                [
                    'name' => 'options[contact_us_icon_bg_color]',
                    'id' => 'contact_us_icon_bg_color',
                    'type' => 'color-picker',
                    'label' => 'Icon Background Color',
                    'default' => '#F2F3FF',
                ],
                [
                    'name' => 'options[contact_us_desc]',
                    'id' => 'contact_us_desc',
                    'type' => 'simple-html-editor',
                    'group_width' => 'full',
                    'label' => 'Description',
                    'default' => 'Nuestro equipo está aquí para ayudarte, ponte en contacto con nosotros y te daremos respuesta lo antes posible.',
                ],
                [
                    'name' => 'options[contact_us_btn_label]',
                    'id' => 'contact_us_btn_label',
                    'type' => 'text',
                    'label' => 'Button Label',
                    'default' => 'Contactar',
                ],
            ],
        ],
    ],
    'components/polygonsearch' => [
        [
            'section_title' => 'Polygon Search',
            'section_description' => '',
            'fields' => [
                [
                    'name' => 'options[polygon_search_title]',
                    'id' => 'polygon_search_title',
                    'type' => 'text',
                    'label' => 'Polygon Search Title',
                    'default' => 'Dibuja tu zona de búsqueda',
                ],
                [
                    'name' => 'options[polygon_search_disabled_text]',
                    'id' => 'polygon_search_disabled_text',
                    'type' => 'text',
                    'label' => 'Search disabled text',
                    'default' => 'Acerca el mapa a la zona que te interese antes de empezar a dibujar.',
                ],
                [
                    'name' => 'options[polygon_search_enabled_text]',
                    'id' => 'polygon_search_enabled_text',
                    'type' => 'text',
                    'label' => 'Search enabled text',
                    'default' => 'Haz clic en el mapa para dibujar tu zona de interés.',
                ],
                [
                    'name' => 'options[polygon_search_enabled_button_text]',
                    'id' => 'polygon_search_enabled_button_text',
                    'type' => 'text',
                    'label' => 'Search button text',
                    'default' => 'Dibuja tu zona',
                ],
                [
                    'name' => 'options[polygon_search_cancel_button_text]',
                    'id' => 'polygon_search_cancel_button_text',
                    'type' => 'text',
                    'label' => 'Search button cancel text',
                    'default' => 'Cancelar',
                ],
                [
                    'name' => 'options[polygon_search_draw_again_text]',
                    'id' => 'polygon_search_draw_again_text',
                    'type' => 'text',
                    'label' => 'Draw polygon again text',
                    'default' => 'La zona dibujada es demasiado grande. Por favor, dibuja una zona más pequeña.',
                ],
            ],
        ]
    ],
];
